import { createStitches } from '@stitches/react'

/**
 * Stitches configuration with Figma tokens
 * All tokens are available as CSS variables and can be accessed via $ prefix
 * Updated with enhanced token system, themeMap, and typography combinations
 */
export const {
  styled,
  css,
  getCssText,
  theme,
  createTheme,
  globalCss,
  keyframes,
  config,
} = createStitches({
  prefix: 'v1',
  
  theme: {
    // Space tokens (using xBase)
    space: {
      // Base token for calculations
      xBase: 'var(--x-base-100)', // 4px base
      
      // Direct xBase tokens
      x0: 'var(--x-base-0)',
      x50: 'var(--x-base-50)',
      x100: 'var(--x-base-100)',
      x200: 'var(--x-base-200)',
      x300: 'var(--x-base-300)',
      x400: 'var(--x-base-400)',
      x500: 'var(--x-base-500)',
      x600: 'var(--x-base-600)',
      x700: 'var(--x-base-700)',
      x800: 'var(--x-base-800)',
      x900: 'var(--x-base-900)',
      x1000: 'var(--x-base-1000)',
      x1100: 'var(--x-base-1100)',
      x1200: 'var(--x-base-1200)',
      x1300: 'var(--x-base-1300)',
      x1400: 'var(--x-base-1400)',
      x1500: 'var(--x-base-1500)',
      x1600: 'var(--x-base-1600)',
      x1700: 'var(--x-base-1700)',
      x1800: 'var(--x-base-1800)',
      x1900: 'var(--x-base-1900)',
      x2000: 'var(--x-base-2000)',
      
      // Computed tokens (using calc with CSS variables)
      x05: 'calc(var(--x-base-100) / 2)',
      x1: 'calc(var(--x-base-100) * 1)',
      x2: 'calc(var(--x-base-100) * 2)',
      x3: 'calc(var(--x-base-100) * 3)',
      x4: 'calc(var(--x-base-100) * 4)',
      x5: 'calc(var(--x-base-100) * 5)',
      x6: 'calc(var(--x-base-100) * 6)',
      x7: 'calc(var(--x-base-100) * 7)',
      x8: 'calc(var(--x-base-100) * 8)',
      x9: 'calc(var(--x-base-100) * 9)',
      x10: 'calc(var(--x-base-100) * 10)',
      x11: 'calc(var(--x-base-100) * 11)',
      x12: 'calc(var(--x-base-100) * 12)',
      x13: 'calc(var(--x-base-100) * 13)',
      x14: 'calc(var(--x-base-100) * 14)',
      x15: 'calc(var(--x-base-100) * 15)',
      x16: 'calc(var(--x-base-100) * 16)',
      x17: 'calc(var(--x-base-100) * 17)',
      x18: 'calc(var(--x-base-100) * 18)',
      x19: 'calc(var(--x-base-100) * 19)',
      x20: 'calc(var(--x-base-100) * 20)',
      
      // Semantic size names
      xxxs: 'calc(var(--x-base-100) / 2)',
      xxs: 'calc(var(--x-base-100) * 1)',
      xs: 'calc(var(--x-base-100) * 2)',
      sm: 'calc(var(--x-base-100) * 3)',
      md: 'calc(var(--x-base-100) * 4)',
      lg: 'calc(var(--x-base-100) * 6)',
      xl: 'calc(var(--x-base-100) * 8)',
      xxl: 'calc(var(--x-base-100) * 10)',
      xxxl: 'calc(var(--x-base-100) * 12)',
      
      // Gravity system spaces (for components)
      'body-m-medium': 'var(--spaces-gravity-system-body-m-medium)',
      'body-m-small': 'var(--spaces-gravity-system-body-m-small)',
      'body-m-tiny': 'var(--spaces-gravity-system-body-m-tiny)',
      'body-m-large': 'var(--spaces-gravity-system-body-m-large)',
      'body-s-medium': 'var(--spaces-gravity-system-body-s-medium)',
      'body-s-small': 'var(--spaces-gravity-system-body-s-small)',
      'body-s-tiny': 'var(--spaces-gravity-system-body-s-tiny)',
      'body-l-medium': 'var(--spaces-gravity-system-body-l-medium)',
      'body-l-small': 'var(--spaces-gravity-system-body-l-small)',
      'body-l-tiny': 'var(--spaces-gravity-system-body-l-tiny)',
      'body-l-large': 'var(--spaces-gravity-system-body-l-large)',
      
      // Typography-based spaces (computed from line heights)
      bodyXL: 'calc(var(--line-heights-x4) + var(--x-base-100))',
      bodyL: 'calc(var(--line-heights-x3) + var(--x-base-100))',
      bodyM: 'calc(var(--line-heights-x2) + var(--x-base-100))',
      bodyS: 'calc(var(--line-heights-x1) + var(--x-base-100))',
      headlineXL: 'calc(var(--line-heights-x6) + var(--x-base-200))',
      headlineL: 'calc(var(--line-heights-x5) + var(--x-base-200))',
      headlineM: 'calc(var(--line-heights-x4) + var(--x-base-100))',
      headlineS: 'calc(var(--line-heights-x3) + var(--x-base-100))',
      headlineXS: 'calc(var(--line-heights-x2) + var(--x-base-100))',
      headlineXXS: 'calc(var(--line-heights-x1) + var(--x-base-100))',
      displayXL: 'calc(var(--line-heights-x9) + var(--x-base-200))',
      displayL: 'calc(var(--line-heights-x8) + var(--x-base-200))',
      displayM: 'calc(var(--line-heights-x7) + var(--x-base-200))',
      displayS: 'calc(var(--line-heights-x6) + var(--x-base-200))',
    },

    // Sizes (same as space for convenience)
    sizes: {
      xBase: 'var(--x-base-100)',
      x0: 'var(--x-base-0)',
      x50: 'var(--x-base-50)',
      x100: 'var(--x-base-100)',
      x200: 'var(--x-base-200)',
      x300: 'var(--x-base-300)',
      x400: 'var(--x-base-400)',
      x500: 'var(--x-base-500)',
      x600: 'var(--x-base-600)',
      x700: 'var(--x-base-700)',
      x800: 'var(--x-base-800)',
      x900: 'var(--x-base-900)',
      x1000: 'var(--x-base-1000)',
      x1100: 'var(--x-base-1100)',
      x1200: 'var(--x-base-1200)',
      x1300: 'var(--x-base-1300)',
      x1400: 'var(--x-base-1400)',
      x1500: 'var(--x-base-1500)',
      x1600: 'var(--x-base-1600)',
      x1700: 'var(--x-base-1700)',
      x1800: 'var(--x-base-1800)',
      x1900: 'var(--x-base-1900)',
      x2000: 'var(--x-base-2000)',
      
      // Computed tokens
      x05: 'calc(var(--x-base-100) / 2)',
      x1: 'calc(var(--x-base-100) * 1)',
      x2: 'calc(var(--x-base-100) * 2)',
      x3: 'calc(var(--x-base-100) * 3)',
      x4: 'calc(var(--x-base-100) * 4)',
      x5: 'calc(var(--x-base-100) * 5)',
      x6: 'calc(var(--x-base-100) * 6)',
      x7: 'calc(var(--x-base-100) * 7)',
      x8: 'calc(var(--x-base-100) * 8)',
      x9: 'calc(var(--x-base-100) * 9)',
      x10: 'calc(var(--x-base-100) * 10)',
      x11: 'calc(var(--x-base-100) * 11)',
      x12: 'calc(var(--x-base-100) * 12)',
      x13: 'calc(var(--x-base-100) * 13)',
      x14: 'calc(var(--x-base-100) * 14)',
      x15: 'calc(var(--x-base-100) * 15)',
      x16: 'calc(var(--x-base-100) * 16)',
      x17: 'calc(var(--x-base-100) * 17)',
      x18: 'calc(var(--x-base-100) * 18)',
      x19: 'calc(var(--x-base-100) * 19)',
      x20: 'calc(var(--x-base-100) * 20)',
      
      // Semantic size names
      xxxs: 'calc(var(--x-base-100) / 2)',
      xxs: 'calc(var(--x-base-100) * 1)',
      xs: 'calc(var(--x-base-100) * 2)',
      sm: 'calc(var(--x-base-100) * 3)',
      md: 'calc(var(--x-base-100) * 4)',
      lg: 'calc(var(--x-base-100) * 6)',
      xl: 'calc(var(--x-base-100) * 8)',
      xxl: 'calc(var(--x-base-100) * 10)',
      xxxl: 'calc(var(--x-base-100) * 12)',
      
      // Gravity system sizes (computed from line heights)
      'bodyS_tiny': 'calc(var(--line-heights-body-s-tight) - var(--x-base-300))',
      'bodyS_small': 'calc(var(--line-heights-body-s-tight) - var(--x-base-200))',
      'bodyS_medium': 'calc(var(--line-heights-body-s-tight) - var(--x-base-100))',
      'bodyS_large': 'var(--line-heights-body-s-tight)',
      'bodyS_huge': 'calc(var(--line-heights-body-s-tight) + var(--x-base-100))',
      'bodyS_paragraph': 'var(--line-heights-body-s-paragraph)',
      'bodyM_tiny': 'calc(var(--line-heights-body-m-tight) - var(--x-base-300))',
      'bodyM_small': 'calc(var(--line-heights-body-m-tight) - var(--x-base-200))',
      'bodyM_medium': 'calc(var(--line-heights-body-m-tight) - var(--x-base-100))',
      'bodyM_large': 'var(--line-heights-body-m-tight)',
      'bodyM_huge': 'calc(var(--line-heights-body-m-tight) + var(--x-base-100))',
      'bodyM_paragraph': 'var(--line-heights-body-m-paragraph)',
      'bodyL_tiny': 'calc(var(--line-heights-body-l-tight) - var(--x-base-300))',
      'bodyL_small': 'calc(var(--line-heights-body-l-tight) - var(--x-base-200))',
      'bodyL_medium': 'calc(var(--line-heights-body-l-tight) - var(--x-base-100))',
      'bodyL_large': 'var(--line-heights-body-l-tight)',
      'bodyL_huge': 'calc(var(--line-heights-body-l-tight) + var(--x-base-100))',
      'bodyL_paragraph': 'var(--line-heights-body-l-paragraph)',
      'bodyXL_tiny': 'calc(var(--line-heights-body-x-l-tight) - var(--x-base-300))',
      'bodyXL_small': 'calc(var(--line-heights-body-x-l-tight) - var(--x-base-200))',
      'bodyXL_medium': 'calc(var(--line-heights-body-x-l-tight) - var(--x-base-100))',
      'bodyXL_large': 'var(--line-heights-body-x-l-tight)',
      'bodyXL_huge': 'calc(var(--line-heights-body-x-l-tight) + var(--x-base-100))',
      'bodyXL_paragraph': 'var(--line-heights-body-x-l-paragraph)',
    },

    // Font sizes
    fontSizes: {
      // Body sizes
      bodyS: 'var(--font-sizes-body-s)',
      bodyM: 'var(--font-sizes-body-m)',
      bodyL: 'var(--font-sizes-body-l)',
      bodyXL: 'var(--font-sizes-body-x-l)',
      // Headline sizes
      headlineS: 'var(--font-sizes-headline-s)',
      headlineM: 'var(--font-sizes-headline-m)',
      headlineL: 'var(--font-sizes-headline-l)',
      headlineXL: 'var(--font-sizes-headline-x-l)',
      headlineXS: 'var(--font-sizes-headline-x-s)',
      headlineXXS: 'var(--font-sizes-headline-x-x-s)',
      // Display sizes
      displayS: 'var(--font-sizes-display-s)',
      displayM: 'var(--font-sizes-display-m)',
      displayL: 'var(--font-sizes-display-l)',
      displayXL: 'var(--font-sizes-display-x-l)',
      // VTB Group sizes
      'vtbGroup-x1': 'var(--font-sizes-vtb-group-x1)',
      'vtbGroup-x2': 'var(--font-sizes-vtb-group-x2)',
      'vtbGroup-x3': 'var(--font-sizes-vtb-group-x3)',
      'vtbGroup-x4': 'var(--font-sizes-vtb-group-x4)',
      'vtbGroup-x5': 'var(--font-sizes-vtb-group-x5)',
      'vtbGroup-x6': 'var(--font-sizes-vtb-group-x6)',
      'vtbGroup-x7': 'var(--font-sizes-vtb-group-x7)',
      'vtbGroup-x8': 'var(--font-sizes-vtb-group-x8)',
      'vtbGroup-x9': 'var(--font-sizes-vtb-group-x9)',
      // Omega UI sizes
      'omegaUI-x1': 'var(--font-sizes-omega-u-i-x1)',
      'omegaUI-x2': 'var(--font-sizes-omega-u-i-x2)',
      'omegaUI-x3': 'var(--font-sizes-omega-u-i-x3)',
      'omegaUI-x4': 'var(--font-sizes-omega-u-i-x4)',
      'omegaUI-x5': 'var(--font-sizes-omega-u-i-x5)',
      'omegaUI-x6': 'var(--font-sizes-omega-u-i-x6)',
      'omegaUI-x7': 'var(--font-sizes-omega-u-i-x7)',
      'omegaUI-x8': 'var(--font-sizes-omega-u-i-x8)',
      'omegaUI-x9': 'var(--font-sizes-omega-u-i-x9)',
    },

    // Line heights
    lineHeights: {
      // Basic line heights
      x1: 'var(--line-heights-x1)',
      x2: 'var(--line-heights-x2)',
      x3: 'var(--line-heights-x3)',
      x4: 'var(--line-heights-x4)',
      x5: 'var(--line-heights-x5)',
      x6: 'var(--line-heights-x6)',
      x7: 'var(--line-heights-x7)',
      x8: 'var(--line-heights-x8)',
      x9: 'var(--line-heights-x9)',
      x10: 'var(--line-heights-x10)',
      x11: 'var(--line-heights-x11)',
      x12: 'var(--line-heights-x12)',
      x13: 'var(--line-heights-x13)',
      // Body line heights
      'body-s-tight': 'var(--line-heights-body-s-tight)',
      'body-s-paragraph': 'var(--line-heights-body-s-paragraph)',
      'body-m-tight': 'var(--line-heights-body-m-tight)',
      'body-m-paragraph': 'var(--line-heights-body-m-paragraph)',
      'body-l-tight': 'var(--line-heights-body-l-tight)',
      'body-l-paragraph': 'var(--line-heights-body-l-paragraph)',
      'body-xl-tight': 'var(--line-heights-body-x-l-tight)',
      'body-xl-paragraph': 'var(--line-heights-body-x-l-paragraph)',
      // Headline line heights
      'headlines-headline-s': 'var(--line-heights-headlines-headline-s)',
      'headlines-headline-m': 'var(--line-heights-headlines-headline-m)',
      'headlines-headline-l': 'var(--line-heights-headlines-headline-l)',
      'headlines-headline-xl': 'var(--line-heights-headlines-headline-x-l)',
      'headlines-headline-xs': 'var(--line-heights-headlines-headline-x-s)',
      'headlines-headline-xxs': 'var(--line-heights-headlines-headline-x-x-s)',
      // Display line heights
      'displays-display-s': 'var(--line-heights-displays-display-s)',
      'displays-display-m': 'var(--line-heights-displays-display-m)',
      'displays-display-l': 'var(--line-heights-displays-display-l)',
      'displays-display-xl': 'var(--line-heights-displays-display-x-l)',
      // Shorthand aliases
      headlineXL: 'var(--line-heights-headlines-headline-x-l)',
      headlineL: 'var(--line-heights-headlines-headline-l)',
      headlineM: 'var(--line-heights-headlines-headline-m)',
      headlineS: 'var(--line-heights-headlines-headline-s)',
      headlineXS: 'var(--line-heights-headlines-headline-x-s)',
      headlineXXS: 'var(--line-heights-headlines-headline-x-x-s)',
      displayXL: 'var(--line-heights-displays-display-x-l)',
      displayL: 'var(--line-heights-displays-display-l)',
      displayM: 'var(--line-heights-displays-display-m)',
      displayS: 'var(--line-heights-displays-display-s)',
    },

    // Letter spacings
    letterSpacings: {
      l0: '0',
      l1: '-0.1px',
      l2: '-0.2px',
      l3: '-0.3px',
    },

    // Fonts
    fonts: {
      sans: 'omegaUI, "omegaUI Fallback", ui-sans-serif, system-ui, sans-serif',
      display: 'omegaUI',
      headline: 'omegaUI',
      body: 'omegaUI',
      vtbGroupUI: 'VTBGroupUI',
    },

    // Font weights
    fontWeights: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      // Token-based weights
      bodyRegular: 'var(--font-weights-body-regular)',
      bodyMedium: 'var(--font-weights-body-medium)',
      bodySemiBold: 'var(--font-weights-body-semi-bold)',
      headline: 'var(--font-weights-headline)',
      display: 'var(--font-weights-display)',
    },

    // Colors - Extended semantic tokens
    colors: {
      // Brand colors
      'brand-primary': 'var(--color-scheme-brand-primary)',
      'brand-secondary': 'var(--color-scheme-brand-secondary)',
      'brand-tertiary': 'var(--color-scheme-brand-tertiary)',
      'brand-text-primary': 'var(--color-scheme-brand-text-primary)',
      'brand-text-secondary': 'var(--color-scheme-brand-text-secondary)',
      'brand-icon-primary': 'var(--color-scheme-brand-icon-primary)',
      'brand-icon-secondary': 'var(--color-scheme-brand-icon-secondary)',
      
      // Background colors
      'bg-secondary-light': 'var(--color-scheme-bg-secondary-light)',
      'bg-secondary-dark': 'var(--color-scheme-bg-secondary-dark)',

      // Button component tokens (filled variant)
      'button-filled-brand-body-normal': 'var(--components-button-filled-brand-body-normal)',
      'button-filled-brand-body-hover': 'var(--components-button-filled-brand-body-hover)',
      'button-filled-brand-body-click': 'var(--components-button-filled-brand-body-click)',
      'button-filled-success-body-normal': 'var(--components-button-filled-success-body-normal)',
      'button-filled-success-body-hover': 'var(--components-button-filled-success-body-hover)',
      'button-filled-success-body-click': 'var(--components-button-filled-success-body-click)',
      'button-filled-info-body-normal': 'var(--components-button-filled-info-body-normal)',
      'button-filled-info-body-hover': 'var(--components-button-filled-info-body-hover)',
      'button-filled-info-body-click': 'var(--components-button-filled-info-body-click)',
      'button-filled-warning-body-normal': 'var(--components-button-filled-warning-body-normal)',
      'button-filled-warning-body-hover': 'var(--components-button-filled-warning-body-hover)',
      'button-filled-warning-body-click': 'var(--components-button-filled-warning-body-click)',
      'button-filled-critical-body-normal': 'var(--components-button-filled-critical-body-normal)',
      'button-filled-critical-body-hover': 'var(--components-button-filled-critical-body-hover)',
      'button-filled-critical-body-click': 'var(--components-button-filled-critical-body-click)',
      'button-filled-neutral-body-normal': 'var(--components-button-filled-neutral-body-normal)',
      'button-filled-neutral-body-hover': 'var(--components-button-filled-neutral-body-hover)',
      'button-filled-neutral-body-click': 'var(--components-button-filled-neutral-body-click)',
      'button-filled-primary-body-normal': 'var(--components-button-filled-primary-body-normal)',
      'button-filled-primary-body-hover': 'var(--components-button-filled-primary-body-hover)',
      'button-filled-primary-body-click': 'var(--components-button-filled-primary-body-click)',
      'button-filled-primary-text': 'var(--components-button-filled-primary-text)',
      'button-filled-primary-icon': 'var(--components-button-filled-primary-icon)',
      'button-filled-constant-body-normal': 'var(--components-button-filled-constant-body-normal)',
      'button-filled-constant-body-hover': 'var(--components-button-filled-constant-body-hover)',
      'button-filled-constant-body-click': 'var(--components-button-filled-constant-body-click)',
      'button-filled-constant-text': 'var(--components-button-filled-constant-text)',
      'button-filled-constant-icon': 'var(--components-button-filled-constant-icon)',
      'button-filled-text': 'var(--components-button-filled-text)',
      'button-filled-icon': 'var(--components-button-filled-icon)',

      // Icon colors
      'semantic-icon-primary': 'var(--semantic-icon-primary)',
      'semantic-icon-primary-inverted': 'var(--semantic-icon-primary-inverted)',
      'semantic-primary-primary': 'var(--semantic-primary-primary)',
      'semantic-primary-60': 'var(--semantic-primary-60)',
      'semantic-primary-70': 'var(--semantic-primary-70)',
      'semantic-neutral-4': 'var(--semantic-neutral-4)',
      'semantic-neutral-8': 'var(--semantic-neutral-8)',
      'semantic-neutral-12': 'var(--semantic-neutral-12)',
      'semantic-neutral-16': 'var(--semantic-neutral-16)',
      'semantic-neutral-24': 'var(--semantic-neutral-24)',
      'semantic-neutral-32': 'var(--semantic-neutral-32)',
      'semantic-neutral-40': 'var(--semantic-neutral-40)',
      'semantic-warning-4': 'var(--semantic-warning-4)',
      'semantic-warning-8': 'var(--semantic-warning-8)',
      'semantic-warning-12': 'var(--semantic-warning-12)',
      'semantic-warning-16': 'var(--semantic-warning-16)',
      'semantic-warning-24': 'var(--semantic-warning-24)',
      'semantic-warning-32': 'var(--semantic-warning-32)',
      'semantic-warning-40': 'var(--semantic-warning-40)',
      'semantic-text-secondary': 'var(--semantic-text-secondary)',
      'semantic-text-warning': 'var(--semantic-text-warning)',

      // Palette colors (commonly used)
      'venusOrange-0': 'var(--venus-orange-0)',
      'venusOrange-50': 'var(--venus-orange-50)',
      'venusOrange-100': 'var(--venus-orange-100)',
      'venusOrange-200': 'var(--venus-orange-200)',
      'venusOrange-300': 'var(--venus-orange-300)',
      'venusOrange-400': 'var(--venus-orange-400)',
      'venusOrange-500': 'var(--venus-orange-500)',
      'venusOrange-600': 'var(--venus-orange-600)',
      'venusOrange-700': 'var(--venus-orange-700)',
      'venusOrange-800': 'var(--venus-orange-800)',
      'venusOrange-900': 'var(--venus-orange-900)',
      'venusOrange-950': 'var(--venus-orange-950)',
      'venusOrange-1000': 'var(--venus-orange-1000)',

      // Gradient colors
      'gradients-aqua': 'var(--gradients-aqua)',
      'gradients-blue': 'var(--gradients-blue)',
      'gradients-green': 'var(--gradients-green)',
      'gradients-lime': 'var(--gradients-lime)',
      'gradients-mgray': 'var(--gradients-mgray)',
      'gradients-orange': 'var(--gradients-orange)',
      'gradients-pink': 'var(--gradients-pink)',
      'gradients-purple': 'var(--gradients-purple)',
      'gradients-red': 'var(--gradients-red)',
      'gradients-rgray': 'var(--gradients-rgray)',
      'gradients-ruby': 'var(--gradients-ruby)',
      'gradients-saphire': 'var(--gradients-saphire)',
      'gradients-teal': 'var(--gradients-teal)',
      'gradients-tgray': 'var(--gradients-tgray)',
      'gradients-yellow': 'var(--gradients-yellow)',

      // Avatar color schemes
      'avatar-brand': 'var(--color-scheme-brand-primary)',
      'avatar-primary': 'var(--semantic-primary-primary)',

      // Bubble colors
      'bubble-text': 'var(--components-bubble-text)',
      'bubble-body-primary': 'var(--components-bubble-body-primary)',
      'bubble-body-brand': 'var(--components-bubble-body-brand)',
      'bubble-body-success': 'var(--components-bubble-body-success)',
      'bubble-body-info': 'var(--components-bubble-body-info)',
      'bubble-body-warning': 'var(--components-bubble-body-warning)',
      'bubble-body-critical': 'var(--components-bubble-body-critical)',
      'bubble-body-neutral': 'var(--components-bubble-body-neutral)',

      // Input component tokens
      'input-body': 'var(--components-input-body)',
      'input-body-disabled': 'var(--components-input-body-disabled)',
      'input-border-normal': 'var(--components-input-border-normal)',
      'input-border-hover': 'var(--components-input-border-hover)',
      'input-border-click': 'var(--components-input-border-click)',
      'input-border-active': 'var(--components-input-border-active)',
      'input-border-filled': 'var(--components-input-border-filled)',
      'input-border-warning': 'var(--components-input-border-warning)',
      'input-border-disabled': 'var(--components-input-border-disabled)',
      'input-border-read-only': 'var(--components-input-border-read-only)',
      'input-text-placeholder': 'var(--components-input-text-placeholder)',
      'input-text-value': 'var(--components-input-text-value)',
      'input-text-value-disabled': 'var(--components-input-text-value-disabled)',
      'input-text-additional': 'var(--components-input-text-additional)',
      'input-text-description': 'var(--components-input-text-description)',
      'input-icon': 'var(--components-input-icon)',
      'input-icon-disabled': 'var(--components-input-icon-disabled)',

      // Add more colors as needed from tokens.css
      // All colors are available via CSS variables
    },

    // Border radius
    radii: {
      // Basic radii (xBase based)
      x0: '0',
      x05: '2px',
      x1: 'var(--spaces-static-x1)', // 4px
      x2: 'var(--spaces-static-x2)', // 8px
      x3: 'var(--spaces-static-x3)', // 12px
      x4: 'var(--spaces-static-x4)', // 16px
      x5: '20px',
      x6: '24px',
      x7: '28px',
      x8: '28px',
      x9: '36px',
      x10: '40px',
      infinite: '9999px',
      // Gravity system radii (body-s)
      'body-s-tiny': 'var(--radii-gravity-system-body-s-tiny)',
      'body-s-small': 'var(--radii-gravity-system-body-s-small)',
      'body-s-medium': 'var(--radii-gravity-system-body-s-medium)',
      'body-s-large': 'var(--radii-gravity-system-body-s-large)',
      'body-s-huge': 'var(--radii-gravity-system-body-s-huge)',
      // Gravity system radii (body-m)
      'body-m-tiny': 'var(--radii-gravity-system-body-m-tiny)',
      'body-m-small': 'var(--radii-gravity-system-body-m-small)',
      'body-m-medium': 'var(--radii-gravity-system-body-m-medium)',
      'body-m-large': 'var(--radii-gravity-system-body-m-large)',
      'body-m-huge': 'var(--radii-gravity-system-body-m-huge)',
      // Gravity system radii (body-l)
      'body-l-tiny': 'var(--radii-gravity-system-body-l-tiny)',
      'body-l-small': 'var(--radii-gravity-system-body-l-small)',
      'body-l-medium': 'var(--radii-gravity-system-body-l-medium)',
      'body-l-large': 'var(--radii-gravity-system-body-l-large)',
      'body-l-huge': 'var(--radii-gravity-system-body-l-huge)',
    },

    // Shadows
    shadows: {
      xxs: '0px 1px 1px hsla(216, 12%, 15%, 0.24)',
      sm: '0px 1px 1px hsla(216, 12%, 15%, 0.04), 0px 1px 2px hsla(216, 12%, 15%, 0.12), 0px 4px 8px hsla(216, 12%, 15%, 0.12)',
      md: '0px 1px 1px hsla(216, 12%, 15%, 0.04), 0px 1px 2px hsla(216, 12%, 15%, 0.12), 0px 8px 16px hsla(216, 12%, 15%, 0.16)',
      lg: '0px 1px 1px hsla(216, 12%, 15%, 0.04), 0px 1px 2px hsla(216, 12%, 15%, 0.12), 0px 12px 24px hsla(216, 12%, 15%, 0.24)',
    },

    // Z-indices
    zIndices: {
      elevation0: '1',
      elevation1: '5',
      elevation2: '10',
      elevation3: '15',
      background0: 'calc(1 - 1)',
      background1: 'calc(5 - 1)',
      background2: 'calc(10 - 1)',
      background3: 'calc(15 - 1)',
    },

    // Transitions
    transitions: {
      short: '0.2s ease-in-out',
    },

    // Border widths
    borderWidths: {
      thin: '1px',
      medium: '2px',
      thick: '4px',
    },

    // Border styles
    borderStyles: {
      solid: 'solid',
      dashed: 'dashed',
      dotted: 'dotted',
    },
  },

  media: {
    xxs: '(min-width: 320px)',
    xs: '(min-width: 375px)',
    sm: '(min-width: 640px)',
    md: '(min-width: 768px)',
    lg: '(min-width: 1024px)',
    xl: '(min-width: 1280px)',
    '2xl': '(min-width: 1536px)',
  },

  themeMap: {
    // Space mappings
    gap: 'space',
    gridGap: 'space',
    columnGap: 'space',
    gridColumnGap: 'space',
    rowGap: 'space',
    gridRowGap: 'space',
    inset: 'space',
    insetBlock: 'space',
    insetBlockEnd: 'space',
    insetBlockStart: 'space',
    insetInline: 'space',
    insetInlineEnd: 'space',
    insetInlineStart: 'space',
    margin: 'space',
    marginTop: 'space',
    marginRight: 'space',
    marginBottom: 'space',
    marginLeft: 'space',
    marginBlock: 'space',
    marginBlockEnd: 'space',
    marginBlockStart: 'space',
    marginInline: 'space',
    marginInlineEnd: 'space',
    marginInlineStart: 'space',
    padding: 'space',
    paddingTop: 'space',
    paddingRight: 'space',
    paddingBottom: 'space',
    paddingLeft: 'space',
    paddingBlock: 'space',
    paddingBlockEnd: 'space',
    paddingBlockStart: 'space',
    paddingInline: 'space',
    paddingInlineEnd: 'space',
    paddingInlineStart: 'space',
    top: 'space',
    right: 'space',
    bottom: 'space',
    left: 'space',
    scrollMargin: 'space',
    scrollMarginTop: 'space',
    scrollMarginRight: 'space',
    scrollMarginBottom: 'space',
    scrollMarginLeft: 'space',
    scrollMarginX: 'space',
    scrollMarginY: 'space',
    scrollMarginBlock: 'space',
    scrollMarginBlockEnd: 'space',
    scrollMarginBlockStart: 'space',
    scrollMarginInline: 'space',
    scrollMarginInlineEnd: 'space',
    scrollMarginInlineStart: 'space',
    scrollPadding: 'space',
    scrollPaddingTop: 'space',
    scrollPaddingRight: 'space',
    scrollPaddingBottom: 'space',
    scrollPaddingLeft: 'space',
    scrollPaddingX: 'space',
    scrollPaddingY: 'space',
    scrollPaddingBlock: 'space',
    scrollPaddingBlockEnd: 'space',
    scrollPaddingBlockStart: 'space',
    scrollPaddingInline: 'space',
    scrollPaddingInlineEnd: 'space',
    scrollPaddingInlineStart: 'space',
    
    // Color mappings
    fontSize: 'fontSizes',
    background: 'colors',
    backgroundColor: 'colors',
    backgroundImage: 'colors',
    borderImage: 'colors',
    border: 'colors',
    borderBlock: 'colors',
    borderBlockEnd: 'colors',
    borderBlockStart: 'colors',
    borderBottom: 'colors',
    borderBottomColor: 'colors',
    borderColor: 'colors',
    borderInline: 'colors',
    borderInlineEnd: 'colors',
    borderInlineStart: 'colors',
    borderLeft: 'colors',
    borderLeftColor: 'colors',
    borderRight: 'colors',
    borderRightColor: 'colors',
    borderTop: 'colors',
    borderTopColor: 'colors',
    caretColor: 'colors',
    color: 'colors',
    columnRuleColor: 'colors',
    fill: 'colors',
    outline: 'colors',
    outlineColor: 'colors',
    stroke: 'colors',
    textDecorationColor: 'colors',
    
    // Typography mappings
    fontFamily: 'fonts',
    fontWeight: 'fontWeights',
    lineHeight: 'lineHeights',
    letterSpacing: 'letterSpacings',
    
    // Size mappings
    blockSize: 'sizes',
    minBlockSize: 'sizes',
    maxBlockSize: 'sizes',
    inlineSize: 'sizes',
    minInlineSize: 'sizes',
    maxInlineSize: 'sizes',
    width: 'sizes',
    minWidth: 'sizes',
    maxWidth: 'sizes',
    height: 'sizes',
    minHeight: 'sizes',
    maxHeight: 'sizes',
    flexBasis: 'sizes',
    gridTemplateColumns: 'sizes',
    gridTemplateRows: 'sizes',
    
    // Border mappings
    borderWidth: 'borderWidths',
    borderTopWidth: 'borderWidths',
    borderRightWidth: 'borderWidths',
    borderBottomWidth: 'borderWidths',
    borderLeftWidth: 'borderWidths',
    borderStyle: 'borderStyles',
    borderTopStyle: 'borderStyles',
    borderRightStyle: 'borderStyles',
    borderBottomStyle: 'borderStyles',
    borderLeftStyle: 'borderStyles',
    borderRadius: 'radii',
    borderTopLeftRadius: 'radii',
    borderTopRightRadius: 'radii',
    borderBottomRightRadius: 'radii',
    borderBottomLeftRadius: 'radii',
    
    // Shadow mappings
    boxShadow: 'shadows',
    textShadow: 'shadows',
    
    // Transition mappings
    transition: 'transitions',
    
    // Z-index mappings
    zIndex: 'zIndices',
  },

  utils: {
    // Padding utilities
    px: (value: string) => ({
      paddingLeft: value,
      paddingRight: value,
    }),
    py: (value: string) => ({
      paddingTop: value,
      paddingBottom: value,
    }),
    p: (value: string) => ({
      padding: value,
    }),

    // Margin utilities
    mx: (value: string) => ({
      marginLeft: value,
      marginRight: value,
    }),
    my: (value: string) => ({
      marginTop: value,
      marginBottom: value,
    }),
    m: (value: string) => ({
      margin: value,
    }),

    // Gap utility
    gap: (value: string) => ({
      gap: value,
    }),
  },
})

export type CSS = ReturnType<typeof css>
export type { VariantProps } from '@stitches/react'

/**
 * Typography combinations for easy use
 * These combine fontFamily, fontSize, lineHeight, letterSpacing, and fontWeight
 */
export const typography = {
  inherit: {
    fontSize: 'inherit',
    lineHeight: 'inherit',
    letterSpacing: 'inherit',
    fontWeight: 'inherit',
  },
  displayXL: {
    fontFamily: '$display',
    fontSize: '$displayXL',
    lineHeight: '$displayXL',
    letterSpacing: '$l0',
    fontWeight: '$display',
  },
  displayL: {
    fontFamily: '$display',
    fontSize: '$displayL',
    lineHeight: '$displayL',
    letterSpacing: '$l0',
    fontWeight: '$display',
  },
  displayM: {
    fontFamily: '$display',
    fontSize: '$displayM',
    lineHeight: '$displayM',
    letterSpacing: '$l0',
    fontWeight: '$display',
  },
  displayS: {
    fontFamily: '$display',
    fontSize: '$displayS',
    lineHeight: '$displayS',
    letterSpacing: '$l0',
    fontWeight: '$display',
  },
  headlineXL: {
    fontFamily: '$headline',
    fontSize: '$headlineXL',
    lineHeight: '$headlineXL',
    letterSpacing: '$l0',
    fontWeight: '$headline',
  },
  headlineL: {
    fontFamily: '$headline',
    fontSize: '$headlineL',
    lineHeight: '$headlineL',
    letterSpacing: '$l0',
    fontWeight: '$headline',
  },
  headlineM: {
    fontFamily: '$headline',
    fontSize: '$headlineM',
    lineHeight: '$headlineM',
    letterSpacing: '$l0',
    fontWeight: '$headline',
  },
  headlineS: {
    fontFamily: '$headline',
    fontSize: '$headlineS',
    lineHeight: '$headlineS',
    letterSpacing: '$l0',
    fontWeight: '$headline',
  },
  headlineXS: {
    fontFamily: '$headline',
    fontSize: '$headlineXS',
    lineHeight: '$headlineXS',
    letterSpacing: '$l0',
    fontWeight: '$headline',
  },
  headlineXXS: {
    fontFamily: '$headline',
    fontSize: '$headlineXXS',
    lineHeight: '$headlineXXS',
    letterSpacing: '$l0',
    fontWeight: '$headline',
  },
  bodyXL_tight_normal: {
    fontFamily: '$body',
    fontSize: '$bodyXL',
    lineHeight: '$body-xl-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodyRegular',
  },
  bodyXL_tight_medium: {
    fontFamily: '$body',
    fontSize: '$bodyXL',
    lineHeight: '$body-xl-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodyMedium',
  },
  bodyXL_tight_semiBold: {
    fontFamily: '$body',
    fontSize: '$bodyXL',
    lineHeight: '$body-xl-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodySemiBold',
  },
  bodyXL_paragraph_normal: {
    fontFamily: '$body',
    fontSize: '$bodyXL',
    lineHeight: '$body-xl-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodyRegular',
  },
  bodyXL_paragraph_medium: {
    fontFamily: '$body',
    fontSize: '$bodyXL',
    lineHeight: '$body-xl-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodyMedium',
  },
  bodyXL_paragraph_semiBold: {
    fontFamily: '$body',
    fontSize: '$bodyXL',
    lineHeight: '$body-xl-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodySemiBold',
  },
  bodyL_tight_normal: {
    fontFamily: '$body',
    fontSize: '$bodyL',
    lineHeight: '$body-l-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodyRegular',
  },
  bodyL_tight_medium: {
    fontFamily: '$body',
    fontSize: '$bodyL',
    lineHeight: '$body-l-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodyMedium',
  },
  bodyL_tight_semiBold: {
    fontFamily: '$body',
    fontSize: '$bodyL',
    lineHeight: '$body-l-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodySemiBold',
  },
  bodyL_paragraph_normal: {
    fontFamily: '$body',
    fontSize: '$bodyL',
    lineHeight: '$body-l-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodyRegular',
  },
  bodyL_paragraph_medium: {
    fontFamily: '$body',
    fontSize: '$bodyL',
    lineHeight: '$body-l-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodyMedium',
  },
  bodyL_paragraph_semiBold: {
    fontFamily: '$body',
    fontSize: '$bodyL',
    lineHeight: '$body-l-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodySemiBold',
  },
  bodyM_tight_normal: {
    fontFamily: '$body',
    fontSize: '$bodyM',
    lineHeight: '$body-m-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodyRegular',
  },
  bodyM_tight_medium: {
    fontFamily: '$body',
    fontSize: '$bodyM',
    lineHeight: '$body-m-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodyMedium',
  },
  bodyM_tight_semiBold: {
    fontFamily: '$body',
    fontSize: '$bodyM',
    lineHeight: '$body-m-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodySemiBold',
  },
  bodyM_paragraph_normal: {
    fontFamily: '$body',
    fontSize: '$bodyM',
    lineHeight: '$body-m-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodyRegular',
  },
  bodyM_paragraph_medium: {
    fontFamily: '$body',
    fontSize: '$bodyM',
    lineHeight: '$body-m-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodyMedium',
  },
  bodyM_paragraph_semiBold: {
    fontFamily: '$body',
    fontSize: '$bodyM',
    lineHeight: '$body-m-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodySemiBold',
  },
  bodyS_tight_normal: {
    fontFamily: '$body',
    fontSize: '$bodyS',
    lineHeight: '$body-s-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodyRegular',
  },
  bodyS_tight_medium: {
    fontFamily: '$body',
    fontSize: '$bodyS',
    lineHeight: '$body-s-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodyMedium',
  },
  bodyS_tight_semiBold: {
    fontFamily: '$body',
    fontSize: '$bodyS',
    lineHeight: '$body-s-tight',
    letterSpacing: '$l0',
    fontWeight: '$bodySemiBold',
  },
  bodyS_paragraph_normal: {
    fontFamily: '$body',
    fontSize: '$bodyS',
    lineHeight: '$body-s-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodyRegular',
  },
  bodyS_paragraph_medium: {
    fontFamily: '$body',
    fontSize: '$bodyS',
    lineHeight: '$body-s-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodyMedium',
  },
  bodyS_paragraph_semiBold: {
    fontFamily: '$body',
    fontSize: '$bodyS',
    lineHeight: '$body-s-paragraph',
    letterSpacing: '$l0',
    fontWeight: '$bodySemiBold',
  },
} as const

// Alias for typographyStyles (for backward compatibility)
export const typographyStyles = typography
