import { d as e } from "./disableSelectionStyles-CytrjT8n.js";
import { s as a, t as i, a as d } from "./stitches.config.es-D33rOtOO.js";
const s = a("button", {
        ...e,
        position: "relative",
        display: "inline-flex",
        flexDirection: "row",
        alignItems: "center",
        columnGap: i.sizes.x3,
        justifyContent: "center",
        background: "none",
        border: "none",
        outlineOffset: 2,
        cursor: "pointer",
        width: "100%",
        "-webkit-tap-highlight-color": "transparent",
        variants: {
            typography: {
                bodyS: { borderRadius: i.radii.x2, ...d.bodyS_tight_medium, "& svg": { fontSize: i.sizes.x4 } },
                bodyM: { borderRadius: i.radii.x3, ...d.bodyM_tight_medium, "& svg": { fontSize: i.sizes.x5 } },
                bodyL: { borderRadius: i.radii.x4, ...d.bodyL_tight_medium, "& svg": { fontSize: i.sizes.x6 } },
            },
            fullWidth: { adaptive: { "@sm": { width: "auto" } }, enable: {}, disable: { width: "auto" } },
            extraPadding: { true: {} },
            paddingSize: { medium: {}, small: {}, tiny: {} },
            rounded: { true: {} },
        },
        compoundVariants: [
            { typography: "bodyS", paddingSize: "medium", css: { padding: i.sizes.x3 } },
            { typography: "bodyS", paddingSize: "small", css: { padding: i.sizes.x2 } },
            { typography: "bodyS", paddingSize: "tiny", css: { padding: i.sizes.x1, borderRadius: i.radii.x1 } },
            { typography: "bodyM", paddingSize: "medium", css: { padding: i.sizes.x4 } },
            { typography: "bodyM", paddingSize: "small", css: { padding: i.sizes.x3 } },
            { typography: "bodyM", paddingSize: "tiny", css: { padding: i.sizes.x2, borderRadius: i.radii.x2 } },
            { typography: "bodyL", paddingSize: "medium", css: { padding: i.sizes.x5 } },
            { typography: "bodyL", paddingSize: "small", css: { padding: i.sizes.x4 } },
            { typography: "bodyL", paddingSize: "tiny", css: { padding: i.sizes.x3, borderRadius: i.radii.x2 } },
            {
                typography: "bodyS",
                paddingSize: "medium",
                extraPadding: !0,
                css: { paddingLeft: i.sizes.x5, paddingRight: i.sizes.x5 },
            },
            {
                typography: "bodyS",
                paddingSize: "small",
                extraPadding: !0,
                css: { paddingLeft: i.sizes.x4, paddingRight: i.sizes.x4 },
            },
            {
                typography: "bodyS",
                paddingSize: "tiny",
                extraPadding: !0,
                css: { paddingLeft: i.sizes.x3, paddingRight: i.sizes.x3 },
            },
            {
                typography: "bodyM",
                paddingSize: "medium",
                extraPadding: !0,
                css: { paddingLeft: i.sizes.x6, paddingRight: i.sizes.x6 },
            },
            {
                typography: "bodyM",
                paddingSize: "small",
                extraPadding: !0,
                css: { paddingLeft: i.sizes.x5, paddingRight: i.sizes.x5 },
            },
            {
                typography: "bodyM",
                paddingSize: "tiny",
                extraPadding: !0,
                css: { paddingLeft: i.sizes.x4, paddingRight: i.sizes.x4 },
            },
            {
                typography: "bodyL",
                paddingSize: "medium",
                extraPadding: !0,
                css: { paddingLeft: i.sizes.x7, paddingRight: i.sizes.x7 },
            },
            {
                typography: "bodyL",
                paddingSize: "small",
                extraPadding: !0,
                css: { paddingLeft: i.sizes.x6, paddingRight: i.sizes.x6 },
            },
            {
                typography: "bodyL",
                paddingSize: "tiny",
                extraPadding: !0,
                css: { paddingLeft: i.sizes.x5, paddingRight: i.sizes.x5 },
            },
            { typography: "bodyS", rounded: !0, css: { borderRadius: i.radii.infinite } },
            { typography: "bodyM", rounded: !0, css: { borderRadius: i.radii.infinite } },
            { typography: "bodyL", rounded: !0, css: { borderRadius: i.radii.infinite } },
        ],
        defaultVariants: { typography: "bodyM", paddingSize: "medium", fullWidth: "adaptive" },
    }),
    t = { Container: s };
t.Container.displayName = "Button.Container";
export { t as B };
