// Auto-generated file. Do not edit manually.
// Generated from Figma tokens export.json

export type XBaseMode = '4px' | '5px' | '6px' | '3px'
export type SemanticMode = 'classic' | 'vtbo'

export const tokenPaths = {
  amaltheanPink: {
    0: '--amalthean-pink-0',
    50: '--amalthean-pink-50',
    100: '--amalthean-pink-100',
    200: '--amalthean-pink-200',
    300: '--amalthean-pink-300',
    400: '--amalthean-pink-400',
    500: '--amalthean-pink-500',
    600: '--amalthean-pink-600',
    700: '--amalthean-pink-700',
    800: '--amalthean-pink-800',
    900: '--amalthean-pink-900',
    950: '--amalthean-pink-950',
    1000: '--amalthean-pink-1000',
  },
  andromedanLime: {
    0: '--andromedan-lime-0',
    50: '--andromedan-lime-50',
    100: '--andromedan-lime-100',
    200: '--andromedan-lime-200',
    300: '--andromedan-lime-300',
    400: '--andromedan-lime-400',
    500: '--andromedan-lime-500',
    600: '--andromedan-lime-600',
    700: '--andromedan-lime-700',
    800: '--andromedan-lime-800',
    900: '--andromedan-lime-900',
    950: '--andromedan-lime-950',
    1000: '--andromedan-lime-1000',
  },
  arielRuby: {
    0: '--ariel-ruby-0',
    50: '--ariel-ruby-50',
    100: '--ariel-ruby-100',
    200: '--ariel-ruby-200',
    300: '--ariel-ruby-300',
    400: '--ariel-ruby-400',
    500: '--ariel-ruby-500',
    600: '--ariel-ruby-600',
    700: '--ariel-ruby-700',
    800: '--ariel-ruby-800',
    900: '--ariel-ruby-900',
    950: '--ariel-ruby-950',
    1000: '--ariel-ruby-1000',
  },
  black: '--black',
  callistianGreen: {
    0: '--callistian-green-0',
    50: '--callistian-green-50',
    100: '--callistian-green-100',
    200: '--callistian-green-200',
    300: '--callistian-green-300',
    400: '--callistian-green-400',
    500: '--callistian-green-500',
    600: '--callistian-green-600',
    700: '--callistian-green-700',
    800: '--callistian-green-800',
    900: '--callistian-green-900',
    950: '--callistian-green-950',
    1000: '--callistian-green-1000',
  },
  colorScheme: {
    bg: {
      secondary: {
        dark: '--color-scheme-bg-secondary-dark',
        light: '--color-scheme-bg-secondary-light',
      },
    },
    brand: {
      4: '--color-scheme-brand-4',
      8: '--color-scheme-brand-8',
      12: '--color-scheme-brand-12',
      16: '--color-scheme-brand-16',
      24: '--color-scheme-brand-24',
      32: '--color-scheme-brand-32',
      40: '--color-scheme-brand-40',
      iconPrimary: '--color-scheme-brand-icon-primary',
      iconSecondary: '--color-scheme-brand-icon-secondary',
      primary: '--color-scheme-brand-primary',
      secondary: '--color-scheme-brand-secondary',
      tertiary: '--color-scheme-brand-tertiary',
      textPrimary: '--color-scheme-brand-text-primary',
      textSecondary: '--color-scheme-brand-text-secondary',
      vtboVeiw: '--color-scheme-brand-vtbo-veiw',
    },
  },
  components: {
    accordion: {
      icon: '--components-accordion-icon',
      textDescription: '--components-accordion-text-description',
      textLabel: '--components-accordion-text-label',
      textValue: '--components-accordion-text-value',
      title: '--components-accordion-title',
    },
    airbar: {
      body: '--components-airbar-body',
      iconFalse: '--components-airbar-icon-false',
      iconTrue: '--components-airbar-icon-true',
      textFalse: '--components-airbar-text-false',
      textTrue: '--components-airbar-text-true',
    },
    badge: {
      filled: {
        brand: {
          body: '--components-badge-filled-brand-body',
          icon: '--components-badge-filled-brand-icon',
          text: '--components-badge-filled-brand-text',
        },
        critical: {
          body: '--components-badge-filled-critical-body',
          icon: '--components-badge-filled-critical-icon',
          text: '--components-badge-filled-critical-text',
        },
        info: {
          body: '--components-badge-filled-info-body',
          icon: '--components-badge-filled-info-icon',
          text: '--components-badge-filled-info-text',
        },
        neutral: {
          body: '--components-badge-filled-neutral-body',
          icon: '--components-badge-filled-neutral-icon',
          text: '--components-badge-filled-neutral-text',
        },
        primary: {
          body: '--components-badge-filled-primary-body',
          icon: '--components-badge-filled-primary-icon',
          text: '--components-badge-filled-primary-text',
        },
        success: {
          body: '--components-badge-filled-success-body',
          icon: '--components-badge-filled-success-icon',
          text: '--components-badge-filled-success-text',
        },
        warning: {
          body: '--components-badge-filled-warning-body',
          icon: '--components-badge-filled-warning-icon',
          text: '--components-badge-filled-warning-text',
        },
      },
      outline: {
        brand: {
          body: '--components-badge-outline-brand-body',
          border: '--components-badge-outline-brand-border',
          icon: '--components-badge-outline-brand-icon',
          text: '--components-badge-outline-brand-text',
        },
        critical: {
          body: '--components-badge-outline-critical-body',
          border: '--components-badge-outline-critical-border',
          icon: '--components-badge-outline-critical-icon',
          text: '--components-badge-outline-critical-text',
        },
        info: {
          body: '--components-badge-outline-info-body',
          border: '--components-badge-outline-info-border',
          icon: '--components-badge-outline-info-icon',
          text: '--components-badge-outline-info-text',
        },
        neutral: {
          body: '--components-badge-outline-neutral-body',
          border: '--components-badge-outline-neutral-border',
          icon: '--components-badge-outline-neutral-icon',
          text: '--components-badge-outline-neutral-text',
        },
        primary: {
          body: '--components-badge-outline-primary-body',
          border: '--components-badge-outline-primary-border',
          icon: '--components-badge-outline-primary-icon',
          text: '--components-badge-outline-primary-text',
        },
        success: {
          body: '--components-badge-outline-success-body',
          border: '--components-badge-outline-success-border',
          icon: '--components-badge-outline-success-icon',
          text: '--components-badge-outline-success-text',
        },
        warning: {
          body: '--components-badge-outline-warning-body',
          border: '--components-badge-outline-warning-border',
          icon: '--components-badge-outline-warning-icon',
          text: '--components-badge-outline-warning-text',
        },
      },
      tonned: {
        brand: {
          body: '--components-badge-tonned-brand-body',
          icon: '--components-badge-tonned-brand-icon',
          text: '--components-badge-tonned-brand-text',
        },
        critical: {
          body: '--components-badge-tonned-critical-body',
          icon: '--components-badge-tonned-critical-icon',
          text: '--components-badge-tonned-critical-text',
        },
        info: {
          body: '--components-badge-tonned-info-body',
          icon: '--components-badge-tonned-info-icon',
          text: '--components-badge-tonned-info-text',
        },
        neutral: {
          body: '--components-badge-tonned-neutral-body',
          icon: '--components-badge-tonned-neutral-icon',
          text: '--components-badge-tonned-neutral-text',
        },
        primary: {
          body: '--components-badge-tonned-primary-body',
          icon: '--components-badge-tonned-primary-icon',
          text: '--components-badge-tonned-primary-text',
        },
        success: {
          body: '--components-badge-tonned-success-body',
          icon: '--components-badge-tonned-success-icon',
          text: '--components-badge-tonned-success-text',
        },
        warning: {
          body: '--components-badge-tonned-warning-body',
          icon: '--components-badge-tonned-warning-icon',
          text: '--components-badge-tonned-warning-text',
        },
      },
    },
    bubble: {
      bodyBrand: '--components-bubble-body-brand',
      bodyCritical: '--components-bubble-body-critical',
      bodyInfo: '--components-bubble-body-info',
      bodyNeutral: '--components-bubble-body-neutral',
      bodyPrimary: '--components-bubble-body-primary',
      bodySuccess: '--components-bubble-body-success',
      bodyWarning: '--components-bubble-body-warning',
      text: '--components-bubble-text',
    },
    button: {
      filled: {
        brand: {
          bodyClick: '--components-button-filled-brand-body-click',
          bodyHover: '--components-button-filled-brand-body-hover',
          bodyNormal: '--components-button-filled-brand-body-normal',
        },
        constant: {
          bodyClick: '--components-button-filled-constant-body-click',
          bodyHover: '--components-button-filled-constant-body-hover',
          bodyNormal: '--components-button-filled-constant-body-normal',
          icon: '--components-button-filled-constant-icon',
          text: '--components-button-filled-constant-text',
        },
        critical: {
          bodyClick: '--components-button-filled-critical-body-click',
          bodyHover: '--components-button-filled-critical-body-hover',
          bodyNormal: '--components-button-filled-critical-body-normal',
        },
        icon: '--components-button-filled-icon',
        info: {
          bodyClick: '--components-button-filled-info-body-click',
          bodyHover: '--components-button-filled-info-body-hover',
          bodyNormal: '--components-button-filled-info-body-normal',
        },
        inverted: {
          bodyClick: '--components-button-filled-inverted-body-click',
          bodyHover: '--components-button-filled-inverted-body-hover',
          bodyNormal: '--components-button-filled-inverted-body-normal',
          icon: '--components-button-filled-inverted-icon',
          text: '--components-button-filled-inverted-text',
        },
        neutral: {
          bodyClick: '--components-button-filled-neutral-body-click',
          bodyHover: '--components-button-filled-neutral-body-hover',
          bodyNormal: '--components-button-filled-neutral-body-normal',
        },
        primary: {
          bodyClick: '--components-button-filled-primary-body-click',
          bodyHover: '--components-button-filled-primary-body-hover',
          bodyNormal: '--components-button-filled-primary-body-normal',
          icon: '--components-button-filled-primary-icon',
          text: '--components-button-filled-primary-text',
        },
        success: {
          bodyClick: '--components-button-filled-success-body-click',
          bodyHover: '--components-button-filled-success-body-hover',
          bodyNormal: '--components-button-filled-success-body-normal',
        },
        text: '--components-button-filled-text',
        warning: {
          bodyClick: '--components-button-filled-warning-body-click',
          bodyHover: '--components-button-filled-warning-body-hover',
          bodyNormal: '--components-button-filled-warning-body-normal',
        },
      },
      outlined: {
        body: '--components-button-outlined-body',
        brand: {
          borderClick: '--components-button-outlined-brand-border-click',
          borderHover: '--components-button-outlined-brand-border-hover',
          borderNormal: '--components-button-outlined-brand-border-normal',
          icon: '--components-button-outlined-brand-icon',
          text: '--components-button-outlined-brand-text',
        },
        constant: {
          borderClick: '--components-button-outlined-constant-border-click',
          borderHover: '--components-button-outlined-constant-border-hover',
          borderNormal: '--components-button-outlined-constant-border-normal',
          icon: '--components-button-outlined-constant-icon',
          text: '--components-button-outlined-constant-text',
        },
        critical: {
          borderClick: '--components-button-outlined-critical-border-click',
          borderHover: '--components-button-outlined-critical-border-hover',
          borderNormal: '--components-button-outlined-critical-border-normal',
          icon: '--components-button-outlined-critical-icon',
          text: '--components-button-outlined-critical-text',
        },
        info: {
          borderClick: '--components-button-outlined-info-border-click',
          borderHover: '--components-button-outlined-info-border-hover',
          borderNormal: '--components-button-outlined-info-border-normal',
          icon: '--components-button-outlined-info-icon',
          text: '--components-button-outlined-info-text',
        },
        neutral: {
          borderClick: '--components-button-outlined-neutral-border-click',
          borderHover: '--components-button-outlined-neutral-border-hover',
          borderNormal: '--components-button-outlined-neutral-border-normal',
          icon: '--components-button-outlined-neutral-icon',
          text: '--components-button-outlined-neutral-text',
        },
        primary: {
          borderClick: '--components-button-outlined-primary-border-click',
          borderHover: '--components-button-outlined-primary-border-hover',
          borderNormal: '--components-button-outlined-primary-border-normal',
          icon: '--components-button-outlined-primary-icon',
          text: '--components-button-outlined-primary-text',
        },
        success: {
          borderClick: '--components-button-outlined-success-border-click',
          borderHover: '--components-button-outlined-success-border-hover',
          borderNormal: '--components-button-outlined-success-border-normal',
          icon: '--components-button-outlined-success-icon',
          text: '--components-button-outlined-success-text',
        },
        warning: {
          borderClick: '--components-button-outlined-warning-border-click',
          borderHover: '--components-button-outlined-warning-border-hover',
          borderNormal: '--components-button-outlined-warning-border-normal',
          icon: '--components-button-outlined-warning-icon',
          text: '--components-button-outlined-warning-text',
        },
      },
      text: {
        brand: {
          iconClick: '--components-button-text-brand-icon-click',
          iconHover: '--components-button-text-brand-icon-hover',
          iconNormal: '--components-button-text-brand-icon-normal',
          textClick: '--components-button-text-brand-text-click',
          textHover: '--components-button-text-brand-text-hover',
          textNormal: '--components-button-text-brand-text-normal',
        },
        constant: {
          iconClick: '--components-button-text-constant-icon-click',
          iconHover: '--components-button-text-constant-icon-hover',
          iconNormal: '--components-button-text-constant-icon-normal',
          textClick: '--components-button-text-constant-text-click',
          textHover: '--components-button-text-constant-text-hover',
          textNormal: '--components-button-text-constant-text-normal',
        },
        critical: {
          iconClick: '--components-button-text-critical-icon-click',
          iconHover: '--components-button-text-critical-icon-hover',
          iconNormal: '--components-button-text-critical-icon-normal',
          textClick: '--components-button-text-critical-text-click',
          textHover: '--components-button-text-critical-text-hover',
          textNormal: '--components-button-text-critical-text-normal',
        },
        info: {
          iconClick: '--components-button-text-info-icon-click',
          iconHover: '--components-button-text-info-icon-hover',
          iconNormal: '--components-button-text-info-icon-normal',
          textClick: '--components-button-text-info-text-click',
          textHover: '--components-button-text-info-text-hover',
          textNormal: '--components-button-text-info-text-normal',
        },
        neutral: {
          iconClick: '--components-button-text-neutral-icon-click',
          iconHover: '--components-button-text-neutral-icon-hover',
          iconNormal: '--components-button-text-neutral-icon-normal',
          textClick: '--components-button-text-neutral-text-click',
          textHover: '--components-button-text-neutral-text-hover',
          textNormal: '--components-button-text-neutral-text-normal',
        },
        primary: {
          iconClick: '--components-button-text-primary-icon-click',
          iconHover: '--components-button-text-primary-icon-hover',
          iconNormal: '--components-button-text-primary-icon-normal',
          textClick: '--components-button-text-primary-text-click',
          textHover: '--components-button-text-primary-text-hover',
          textNormal: '--components-button-text-primary-text-normal',
        },
        success: {
          iconClick: '--components-button-text-success-icon-click',
          iconHover: '--components-button-text-success-icon-hover',
          iconNormal: '--components-button-text-success-icon-normal',
          textClick: '--components-button-text-success-text-click',
          textHover: '--components-button-text-success-text-hover',
          textNormal: '--components-button-text-success-text-normal',
        },
        warning: {
          iconClick: '--components-button-text-warning-icon-click',
          iconHover: '--components-button-text-warning-icon-hover',
          iconNormal: '--components-button-text-warning-icon-normal',
          textClick: '--components-button-text-warning-text-click',
          textHover: '--components-button-text-warning-text-hover',
          textNormal: '--components-button-text-warning-text-normal',
        },
      },
      tonned: {
        brand: {
          bodyClick: '--components-button-tonned-brand-body-click',
          bodyHover: '--components-button-tonned-brand-body-hover',
          bodyNormal: '--components-button-tonned-brand-body-normal',
          icon: '--components-button-tonned-brand-icon',
          text: '--components-button-tonned-brand-text',
        },
        constant: {
          bodyClick: '--components-button-tonned-constant-body-click',
          bodyHover: '--components-button-tonned-constant-body-hover',
          bodyNormal: '--components-button-tonned-constant-body-normal',
          icon: '--components-button-tonned-constant-icon',
          text: '--components-button-tonned-constant-text',
        },
        critical: {
          bodyClick: '--components-button-tonned-critical-body-click',
          bodyHover: '--components-button-tonned-critical-body-hover',
          bodyNormal: '--components-button-tonned-critical-body-normal',
          icon: '--components-button-tonned-critical-icon',
          text: '--components-button-tonned-critical-text',
        },
        info: {
          bodyClick: '--components-button-tonned-info-body-click',
          bodyHover: '--components-button-tonned-info-body-hover',
          bodyNormal: '--components-button-tonned-info-body-normal',
          icon: '--components-button-tonned-info-icon',
          text: '--components-button-tonned-info-text',
        },
        neutral: {
          bodyClick: '--components-button-tonned-neutral-body-click',
          bodyHover: '--components-button-tonned-neutral-body-hover',
          bodyNormal: '--components-button-tonned-neutral-body-normal',
          icon: '--components-button-tonned-neutral-icon',
          text: '--components-button-tonned-neutral-text',
        },
        primary: {
          bodyClick: '--components-button-tonned-primary-body-click',
          bodyHover: '--components-button-tonned-primary-body-hover',
          bodyNormal: '--components-button-tonned-primary-body-normal',
          icon: '--components-button-tonned-primary-icon',
          text: '--components-button-tonned-primary-text',
        },
        success: {
          bodyClick: '--components-button-tonned-success-body-click',
          bodyHover: '--components-button-tonned-success-body-hover',
          bodyNormal: '--components-button-tonned-success-body-normal',
          icon: '--components-button-tonned-success-icon',
          text: '--components-button-tonned-success-text',
        },
        warning: {
          bodyClick: '--components-button-tonned-warning-body-click',
          bodyHover: '--components-button-tonned-warning-body-hover',
          bodyNormal: '--components-button-tonned-warning-body-normal',
          icon: '--components-button-tonned-warning-icon',
          text: '--components-button-tonned-warning-text',
        },
      },
      transparent: {
        bodyNormal: '--components-button-transparent-body-normal',
        brand: {
          bodyClick: '--components-button-transparent-brand-body-click',
          bodyHover: '--components-button-transparent-brand-body-hover',
          icon: '--components-button-transparent-brand-icon',
          text: '--components-button-transparent-brand-text',
        },
        constant: {
          bodyClick: '--components-button-transparent-constant-body-click',
          bodyHover: '--components-button-transparent-constant-body-hover',
          icon: '--components-button-transparent-constant-icon',
          text: '--components-button-transparent-constant-text',
        },
        critical: {
          bodyClick: '--components-button-transparent-critical-body-click',
          bodyHover: '--components-button-transparent-critical-body-hover',
          icon: '--components-button-transparent-critical-icon',
          text: '--components-button-transparent-critical-text',
        },
        info: {
          bodyClick: '--components-button-transparent-info-body-click',
          bodyHover: '--components-button-transparent-info-body-hover',
          icon: '--components-button-transparent-info-icon',
          text: '--components-button-transparent-info-text',
        },
        neutral: {
          bodyClick: '--components-button-transparent-neutral-body-click',
          bodyHover: '--components-button-transparent-neutral-body-hover',
          icon: '--components-button-transparent-neutral-icon',
          text: '--components-button-transparent-neutral-text',
        },
        primary: {
          bodyClick: '--components-button-transparent-primary-body-click',
          bodyHover: '--components-button-transparent-primary-body-hover',
          icon: '--components-button-transparent-primary-icon',
          text: '--components-button-transparent-primary-text',
        },
        success: {
          bodyClick: '--components-button-transparent-success-body-click',
          bodyHover: '--components-button-transparent-success-body-hover',
          icon: '--components-button-transparent-success-icon',
          text: '--components-button-transparent-success-text',
        },
        warning: {
          bodyClick: '--components-button-transparent-warning-body-click',
          bodyHover: '--components-button-transparent-warning-body-hover',
          icon: '--components-button-transparent-warning-icon',
          text: '--components-button-transparent-warning-text',
        },
      },
    },
    chips: {
      filled: {
        off: {
          bodyClick: '--components-chips-filled-off-body-click',
          bodyDisabled: '--components-chips-filled-off-body-disabled',
          bodyHover: '--components-chips-filled-off-body-hover',
          bodyNormal: '--components-chips-filled-off-body-normal',
          iconPrimary: '--components-chips-filled-off-icon-primary',
          iconSecondary: '--components-chips-filled-off-icon-secondary',
          text: '--components-chips-filled-off-text',
          textDisabled: '--components-chips-filled-off-text-disabled',
        },
        on: {
          bodyClick: '--components-chips-filled-on-body-click',
          bodyDisabled: '--components-chips-filled-on-body-disabled',
          bodyHover: '--components-chips-filled-on-body-hover',
          bodyNormal: '--components-chips-filled-on-body-normal',
          iconPrimary: '--components-chips-filled-on-icon-primary',
          iconSecondary: '--components-chips-filled-on-icon-secondary',
          text: '--components-chips-filled-on-text',
          textDisabled: '--components-chips-filled-on-text-disabled',
        },
      },
      outlined: {
        off: {
          bodyClick: '--components-chips-outlined-off-body-click',
          bodyDisabled: '--components-chips-outlined-off-body-disabled',
          bodyHover: '--components-chips-outlined-off-body-hover',
          bodyNormal: '--components-chips-outlined-off-body-normal',
          border: '--components-chips-outlined-off-border',
          iconPrimary: '--components-chips-outlined-off-icon-primary',
          iconSecondary: '--components-chips-outlined-off-icon-secondary',
          text: '--components-chips-outlined-off-text',
          textDisabled: '--components-chips-outlined-off-text-disabled',
        },
        on: {
          bodyClick: '--components-chips-outlined-on-body-click',
          bodyDisabled: '--components-chips-outlined-on-body-disabled',
          bodyHover: '--components-chips-outlined-on-body-hover',
          bodyNormal: '--components-chips-outlined-on-body-normal',
          border: '--components-chips-outlined-on-border',
          iconPrimary: '--components-chips-outlined-on-icon-primary',
          iconSecondary: '--components-chips-outlined-on-icon-secondary',
          text: '--components-chips-outlined-on-text',
          textDisabled: '--components-chips-outlined-on-text-disabled',
        },
      },
    },
    divider: {
      fat: '--components-divider-fat',
      thin: '--components-divider-thin',
    },
    hint: {
      body: '--components-hint-body',
      description: '--components-hint-description',
      icon: '--components-hint-icon',
      title: '--components-hint-title',
    },
    informer: {
      brand: {
        body: '--components-informer-brand-body',
        border: '--components-informer-brand-border',
        icon: '--components-informer-brand-icon',
      },
      closeIcon: '--components-informer-close-icon',
      critical: {
        body: '--components-informer-critical-body',
        border: '--components-informer-critical-border',
        icon: '--components-informer-critical-icon',
      },
      description: '--components-informer-description',
      info: {
        body: '--components-informer-info-body',
        border: '--components-informer-info-border',
        icon: '--components-informer-info-icon',
      },
      neutral: {
        body: '--components-informer-neutral-body',
        border: '--components-informer-neutral-border',
        icon: '--components-informer-neutral-icon',
      },
      success: {
        body: '--components-informer-success-body',
        border: '--components-informer-success-border',
        icon: '--components-informer-success-icon',
      },
      text: '--components-informer-text',
      title: '--components-informer-title',
      warning: {
        body: '--components-informer-warning-body',
        border: '--components-informer-warning-border',
        icon: '--components-informer-warning-icon',
      },
    },
    input: {
      body: '--components-input-body',
      bodyDisabled: '--components-input-body-disabled',
      borderActive: '--components-input-border-active',
      borderClick: '--components-input-border-click',
      borderDisabled: '--components-input-border-disabled',
      borderFilled: '--components-input-border-filled',
      borderHover: '--components-input-border-hover',
      borderNormal: '--components-input-border-normal',
      borderReadOnly: '--components-input-border-read-only',
      borderWarning: '--components-input-border-warning',
      icon: '--components-input-icon',
      iconDisabled: '--components-input-icon-disabled',
      textAdditional: '--components-input-text-additional',
      textDescription: '--components-input-text-description',
      textPlaceholder: '--components-input-text-placeholder',
      textValue: '--components-input-text-value',
      textValueDisabled: '--components-input-text-value-disabled',
    },
    link: {
      brand: {
        iconClick: '--components-link-brand-icon-click',
        iconHover: '--components-link-brand-icon-hover',
        iconNormal: '--components-link-brand-icon-normal',
        textClick: '--components-link-brand-text-click',
        textHover: '--components-link-brand-text-hover',
        textNormal: '--components-link-brand-text-normal',
      },
      constant: {
        iconClick: '--components-link-constant-icon-click',
        iconHover: '--components-link-constant-icon-hover',
        iconNormal: '--components-link-constant-icon-normal',
        textClick: '--components-link-constant-text-click',
        textHover: '--components-link-constant-text-hover',
        textNormal: '--components-link-constant-text-normal',
      },
      critical: {
        iconClick: '--components-link-critical-icon-click',
        iconHover: '--components-link-critical-icon-hover',
        iconNormal: '--components-link-critical-icon-normal',
        textClick: '--components-link-critical-text-click',
        textHover: '--components-link-critical-text-hover',
        textNormal: '--components-link-critical-text-normal',
      },
      info: {
        iconClick: '--components-link-info-icon-click',
        iconHover: '--components-link-info-icon-hover',
        iconNormal: '--components-link-info-icon-normal',
        textClick: '--components-link-info-text-click',
        textHover: '--components-link-info-text-hover',
        textNormal: '--components-link-info-text-normal',
      },
      neutral: {
        iconClick: '--components-link-neutral-icon-click',
        iconHover: '--components-link-neutral-icon-hover',
        iconNormal: '--components-link-neutral-icon-normal',
        textClick: '--components-link-neutral-text-click',
        textHover: '--components-link-neutral-text-hover',
        textNormal: '--components-link-neutral-text-normal',
      },
      primary: {
        iconClick: '--components-link-primary-icon-click',
        iconHover: '--components-link-primary-icon-hover',
        iconNormal: '--components-link-primary-icon-normal',
        textClick: '--components-link-primary-text-click',
        textHover: '--components-link-primary-text-hover',
        textNormal: '--components-link-primary-text-normal',
      },
      success: {
        iconClick: '--components-link-success-icon-click',
        iconHover: '--components-link-success-icon-hover',
        iconNormal: '--components-link-success-icon-normal',
        textClick: '--components-link-success-text-click',
        textHover: '--components-link-success-text-hover',
        textNormal: '--components-link-success-text-normal',
      },
      warning: {
        iconClick: '--components-link-warning-icon-click',
        iconHover: '--components-link-warning-icon-hover',
        iconNormal: '--components-link-warning-icon-normal',
        textClick: '--components-link-warning-text-click',
        textHover: '--components-link-warning-text-hover',
        textNormal: '--components-link-warning-text-normal',
      },
    },
    loader: {
      brand: {
        body: '--components-loader-brand-body',
        progress: '--components-loader-brand-progress',
      },
      constant: {
        body: '--components-loader-constant-body',
        progress: '--components-loader-constant-progress',
      },
      constantPrimary: {
        body: '--components-loader-constant-primary-body',
        progress: '--components-loader-constant-primary-progress',
      },
      critical: {
        body: '--components-loader-critical-body',
        progress: '--components-loader-critical-progress',
      },
      info: {
        body: '--components-loader-info-body',
        progress: '--components-loader-info-progress',
      },
      inverted: {
        body: '--components-loader-inverted-body',
        progress: '--components-loader-inverted-progress',
      },
      neutral: {
        body: '--components-loader-neutral-body',
        progress: '--components-loader-neutral-progress',
      },
      primary: {
        body: '--components-loader-primary-body',
        progress: '--components-loader-primary-progress',
      },
      success: {
        body: '--components-loader-success-body',
        progress: '--components-loader-success-progress',
      },
      warning: {
        body: '--components-loader-warning-body',
        progress: '--components-loader-warning-progress',
      },
    },
    progress: {
      filled: {
        background: '--components-progress-filled-background',
        backgroundConstant: '--components-progress-filled-background-constant',
        bodyBrand: '--components-progress-filled-body-brand',
        bodyConstant: '--components-progress-filled-body-constant',
        bodyConstantInverted: '--components-progress-filled-body-constant-inverted',
        bodyCritical: '--components-progress-filled-body-critical',
        bodyInfo: '--components-progress-filled-body-info',
        bodyNeutral: '--components-progress-filled-body-neutral',
        bodyPrimary: '--components-progress-filled-body-primary',
        bodySuccess: '--components-progress-filled-body-success',
        bodyWarning: '--components-progress-filled-body-warning',
      },
    },
    steps: {
      off: {
        bodyClick: '--components-steps-off-body-click',
        bodyHover: '--components-steps-off-body-hover',
        bodyNormal: '--components-steps-off-body-normal',
      },
      on: {
        brand: {
          bodyClick: '--components-steps-on-brand-body-click',
          bodyHover: '--components-steps-on-brand-body-hover',
          bodyNormal: '--components-steps-on-brand-body-normal',
        },
        constant: {
          bodyClick: '--components-steps-on-constant-body-click',
          bodyHover: '--components-steps-on-constant-body-hover',
          bodyNormal: '--components-steps-on-constant-body-normal',
        },
        critical: {
          bodyClick: '--components-steps-on-critical-body-click',
          bodyHover: '--components-steps-on-critical-body-hover',
          bodyNormal: '--components-steps-on-critical-body-normal',
        },
        info: {
          bodyClick: '--components-steps-on-info-body-click',
          bodyHover: '--components-steps-on-info-body-hover',
          bodyNormal: '--components-steps-on-info-body-normal',
        },
        neutral: {
          bodyClick: '--components-steps-on-neutral-body-click',
          bodyHover: '--components-steps-on-neutral-body-hover',
          bodyNormal: '--components-steps-on-neutral-body-normal',
        },
        success: {
          bodyClick: '--components-steps-on-success-body-click',
          bodyHover: '--components-steps-on-success-body-hover',
          bodyNormal: '--components-steps-on-success-body-normal',
        },
        warning: {
          bodyClick: '--components-steps-on-warning-body-click',
          bodyHover: '--components-steps-on-warning-body-hover',
          bodyNormal: '--components-steps-on-warning-body-normal',
        },
      },
    },
    suggest: {
      off: {
        bodyClick: '--components-suggest-off-body-click',
        bodyHover: '--components-suggest-off-body-hover',
        bodyNormal: '--components-suggest-off-body-normal',
        borderClick: '--components-suggest-off-border-click',
        borderHover: '--components-suggest-off-border-hover',
        borderNormal: '--components-suggest-off-border-normal',
        icon: '--components-suggest-off-icon',
        text: '--components-suggest-off-text',
      },
      on: {
        bodyClick: '--components-suggest-on-body-click',
        bodyHover: '--components-suggest-on-body-hover',
        bodyNormal: '--components-suggest-on-body-normal',
        borderClick: '--components-suggest-on-border-click',
        borderHover: '--components-suggest-on-border-hover',
        borderNormal: '--components-suggest-on-border-normal',
        icon: '--components-suggest-on-icon',
        text: '--components-suggest-on-text',
      },
    },
    tab: {
      counterBodyNormal: '--components-tab-counter-body-normal',
      counterText: '--components-tab-counter-text',
      indicator: '--components-tab-indicator',
      off: {
        bodyClick: '--components-tab-off-body-click',
        bodyHover: '--components-tab-off-body-hover',
        bodyNormal: '--components-tab-off-body-normal',
        icon: '--components-tab-off-icon',
        text: '--components-tab-off-text',
      },
      on: {
        bodyClick: '--components-tab-on-body-click',
        bodyHover: '--components-tab-on-body-hover',
        bodyNormal: '--components-tab-on-body-normal',
        icon: '--components-tab-on-icon',
        text: '--components-tab-on-text',
      },
    },
    textField: {
      textDescription: '--components-text-field-text-description',
      textLabel: '--components-text-field-text-label',
      textOptional: '--components-text-field-text-optional',
      textPlaceholder: '--components-text-field-text-placeholder',
      textWarning: '--components-text-field-text-warning',
    },
    toast: {
      body: '--components-toast-body',
      brand: {
        body: '--components-toast-brand-body',
        border: '--components-toast-brand-border',
        icon: '--components-toast-brand-icon',
      },
      closeIcon: '--components-toast-close-icon',
      critical: {
        body: '--components-toast-critical-body',
        border: '--components-toast-critical-border',
        icon: '--components-toast-critical-icon',
      },
      description: '--components-toast-description',
      info: {
        body: '--components-toast-info-body',
        border: '--components-toast-info-border',
        icon: '--components-toast-info-icon',
      },
      neutral: {
        body: '--components-toast-neutral-body',
        border: '--components-toast-neutral-border',
        icon: '--components-toast-neutral-icon',
      },
      success: {
        body: '--components-toast-success-body',
        border: '--components-toast-success-border',
        icon: '--components-toast-success-icon',
      },
      text: '--components-toast-text',
      title: '--components-toast-title',
      warning: {
        body: '--components-toast-warning-body',
        border: '--components-toast-warning-border',
        icon: '--components-toast-warning-icon',
      },
    },
    tooltip: {
      body: '--components-tooltip-body',
      text: '--components-tooltip-text',
    },
    userChoice: {
      off: {
        body: '--components-user-choice-off-body',
        bodyClick: '--components-user-choice-off-body-click',
        bodyDisabled: '--components-user-choice-off-body-disabled',
        bodyHover: '--components-user-choice-off-body-hover',
        bodyNormal: '--components-user-choice-off-body-normal',
        bodyWarning: '--components-user-choice-off-body-warning',
        borderClick: '--components-user-choice-off-border-click',
        borderDisabled: '--components-user-choice-off-border-disabled',
        borderHover: '--components-user-choice-off-border-hover',
        borderNormal: '--components-user-choice-off-border-normal',
      },
      on: {
        bodyClick: '--components-user-choice-on-body-click',
        bodyDisabled: '--components-user-choice-on-body-disabled',
        bodyHover: '--components-user-choice-on-body-hover',
        bodyNormal: '--components-user-choice-on-body-normal',
        bodyWarning: '--components-user-choice-on-body-warning',
      },
      textDescription: '--components-user-choice-text-description',
      textLabel: '--components-user-choice-text-label',
      textValue: '--components-user-choice-text-value',
      textWarning: '--components-user-choice-text-warning',
      toggle: '--components-user-choice-toggle',
      toggleDisabled: '--components-user-choice-toggle-disabled',
    },
  },
  earthyTeal: {
    0: '--earthy-teal-0',
    50: '--earthy-teal-50',
    100: '--earthy-teal-100',
    200: '--earthy-teal-200',
    300: '--earthy-teal-300',
    400: '--earthy-teal-400',
    500: '--earthy-teal-500',
    600: '--earthy-teal-600',
    700: '--earthy-teal-700',
    800: '--earthy-teal-800',
    900: '--earthy-teal-900',
    950: '--earthy-teal-950',
    1000: '--earthy-teal-1000',
  },
  fontFamilies: {
    body: '--font-families-body',
    display: '--font-families-display',
    headline: '--font-families-headline',
  },
  fontSizes: {
    bodyL: '--font-sizes-body-l',
    bodyM: '--font-sizes-body-m',
    bodyS: '--font-sizes-body-s',
    bodyXL: '--font-sizes-body-x-l',
    displayL: '--font-sizes-display-l',
    displayM: '--font-sizes-display-m',
    displayS: '--font-sizes-display-s',
    displayXL: '--font-sizes-display-x-l',
    headlineL: '--font-sizes-headline-l',
    headlineM: '--font-sizes-headline-m',
    headlineS: '--font-sizes-headline-s',
    headlineXL: '--font-sizes-headline-x-l',
    headlineXS: '--font-sizes-headline-x-s',
    headlineXXS: '--font-sizes-headline-x-x-s',
    omegaUI: {
      x1: '--font-sizes-omega-u-i-x1',
      x2: '--font-sizes-omega-u-i-x2',
      x3: '--font-sizes-omega-u-i-x3',
      x4: '--font-sizes-omega-u-i-x4',
      x5: '--font-sizes-omega-u-i-x5',
      x6: '--font-sizes-omega-u-i-x6',
      x7: '--font-sizes-omega-u-i-x7',
      x8: '--font-sizes-omega-u-i-x8',
      x9: '--font-sizes-omega-u-i-x9',
    },
    vtbGroup: {
      x1: '--font-sizes-vtb-group-x1',
      x2: '--font-sizes-vtb-group-x2',
      x3: '--font-sizes-vtb-group-x3',
      x4: '--font-sizes-vtb-group-x4',
      x5: '--font-sizes-vtb-group-x5',
      x6: '--font-sizes-vtb-group-x6',
      x7: '--font-sizes-vtb-group-x7',
      x8: '--font-sizes-vtb-group-x8',
      x9: '--font-sizes-vtb-group-x9',
    },
  },
  fontWeights: {
    bodyMedium: '--font-weights-body-medium',
    bodyRegular: '--font-weights-body-regular',
    bodySemiBold: '--font-weights-body-semi-bold',
    display: '--font-weights-display',
    headline: '--font-weights-headline',
  },
  galaxyPurple: {
    0: '--galaxy-purple-0',
    50: '--galaxy-purple-50',
    100: '--galaxy-purple-100',
    200: '--galaxy-purple-200',
    300: '--galaxy-purple-300',
    400: '--galaxy-purple-400',
    500: '--galaxy-purple-500',
    600: '--galaxy-purple-600',
    700: '--galaxy-purple-700',
    800: '--galaxy-purple-800',
    900: '--galaxy-purple-900',
    950: '--galaxy-purple-950',
    1000: '--galaxy-purple-1000',
  },
  gradients: {
    aqua: '--gradients-aqua',
    blue: '--gradients-blue',
    green: '--gradients-green',
    lime: '--gradients-lime',
    mgray: '--gradients-mgray',
    orange: '--gradients-orange',
    pink: '--gradients-pink',
    purple: '--gradients-purple',
    red: '--gradients-red',
    rgray: '--gradients-rgray',
    ruby: '--gradients-ruby',
    saphire: '--gradients-saphire',
    teal: '--gradients-teal',
    tgray: '--gradients-tgray',
    yellow: '--gradients-yellow',
  },
  letterSpacing: {
    l0: '--letter-spacing-l0',
    l1: '--letter-spacing-l1',
    l2: '--letter-spacing-l2',
  },
  lineHeights: {
    bodyL: {
      paragraph: '--line-heights-body-l-paragraph',
      tight: '--line-heights-body-l-tight',
    },
    bodyM: {
      paragraph: '--line-heights-body-m-paragraph',
      tight: '--line-heights-body-m-tight',
    },
    bodyS: {
      paragraph: '--line-heights-body-s-paragraph',
      tight: '--line-heights-body-s-tight',
    },
    bodyXL: {
      paragraph: '--line-heights-body-x-l-paragraph',
      tight: '--line-heights-body-x-l-tight',
    },
    displays: {
      displayL: '--line-heights-displays-display-l',
      displayM: '--line-heights-displays-display-m',
      displayS: '--line-heights-displays-display-s',
      displayXL: '--line-heights-displays-display-x-l',
    },
    headlines: {
      headlineL: '--line-heights-headlines-headline-l',
      headlineM: '--line-heights-headlines-headline-m',
      headlineS: '--line-heights-headlines-headline-s',
      headlineXL: '--line-heights-headlines-headline-x-l',
      headlineXS: '--line-heights-headlines-headline-x-s',
      headlineXXS: '--line-heights-headlines-headline-x-x-s',
    },
    x1: '--line-heights-x1',
    x10: '--line-heights-x10',
    x11: '--line-heights-x11',
    x12: '--line-heights-x12',
    x13: '--line-heights-x13',
    x2: '--line-heights-x2',
    x3: '--line-heights-x3',
    x4: '--line-heights-x4',
    x5: '--line-heights-x5',
    x6: '--line-heights-x6',
    x7: '--line-heights-x7',
    x8: '--line-heights-x8',
    x9: '--line-heights-x9',
  },
  martianRed: {
    0: '--martian-red-0',
    50: '--martian-red-50',
    100: '--martian-red-100',
    200: '--martian-red-200',
    300: '--martian-red-300',
    400: '--martian-red-400',
    500: '--martian-red-500',
    600: '--martian-red-600',
    700: '--martian-red-700',
    800: '--martian-red-800',
    900: '--martian-red-900',
    950: '--martian-red-950',
    1000: '--martian-red-1000',
  },
  moonGray: {
    0: '--moon-gray-0',
    50: '--moon-gray-50',
    100: '--moon-gray-100',
    200: '--moon-gray-200',
    300: '--moon-gray-300',
    400: '--moon-gray-400',
    500: '--moon-gray-500',
    600: '--moon-gray-600',
    700: '--moon-gray-700',
    800: '--moon-gray-800',
    900: '--moon-gray-900',
    950: '--moon-gray-950',
    1000: '--moon-gray-1000',
  },
  oberonianYellow: {
    0: '--oberonian-yellow-0',
    50: '--oberonian-yellow-50',
    100: '--oberonian-yellow-100',
    200: '--oberonian-yellow-200',
    300: '--oberonian-yellow-300',
    400: '--oberonian-yellow-400',
    500: '--oberonian-yellow-500',
    600: '--oberonian-yellow-600',
    700: '--oberonian-yellow-700',
    800: '--oberonian-yellow-800',
    900: '--oberonian-yellow-900',
    950: '--oberonian-yellow-950',
    1000: '--oberonian-yellow-1000',
  },
  omegaBlue: {
    0: '--omega-blue-0',
    50: '--omega-blue-50',
    100: '--omega-blue-100',
    200: '--omega-blue-200',
    300: '--omega-blue-300',
    400: '--omega-blue-400',
    500: '--omega-blue-500',
    600: '--omega-blue-600',
    700: '--omega-blue-700',
    800: '--omega-blue-800',
    900: '--omega-blue-900',
    950: '--omega-blue-950',
    1000: '--omega-blue-1000',
  },
  opacity: {
    disabled: '--opacity-disabled',
  },
  radii: {
    gravitySystem: {
      bodyL: {
        huge: '--radii-gravity-system-body-l-huge',
        large: '--radii-gravity-system-body-l-large',
        medium: '--radii-gravity-system-body-l-medium',
        small: '--radii-gravity-system-body-l-small',
        tiny: '--radii-gravity-system-body-l-tiny',
      },
      bodyM: {
        huge: '--radii-gravity-system-body-m-huge',
        large: '--radii-gravity-system-body-m-large',
        medium: '--radii-gravity-system-body-m-medium',
        small: '--radii-gravity-system-body-m-small',
        tiny: '--radii-gravity-system-body-m-tiny',
      },
      bodyS: {
        huge: '--radii-gravity-system-body-s-huge',
        large: '--radii-gravity-system-body-s-large',
        medium: '--radii-gravity-system-body-s-medium',
        small: '--radii-gravity-system-body-s-small',
        tiny: '--radii-gravity-system-body-s-tiny',
      },
      bodyXL: {
        huge: '--radii-gravity-system-body-x-l-huge',
        large: '--radii-gravity-system-body-x-l-large',
        medium: '--radii-gravity-system-body-x-l-medium',
        small: '--radii-gravity-system-body-x-l-small',
        tiny: '--radii-gravity-system-body-x-l-tiny',
      },
      displayL: {
        huge: '--radii-gravity-system-display-l-huge',
        large: '--radii-gravity-system-display-l-large',
        medium: '--radii-gravity-system-display-l-medium',
        small: '--radii-gravity-system-display-l-small',
        tiny: '--radii-gravity-system-display-l-tiny',
      },
      displayM: {
        huge: '--radii-gravity-system-display-m-huge',
        large: '--radii-gravity-system-display-m-large',
        medium: '--radii-gravity-system-display-m-medium',
        small: '--radii-gravity-system-display-m-small',
        tiny: '--radii-gravity-system-display-m-tiny',
      },
      displayS: {
        huge: '--radii-gravity-system-display-s-huge',
        large: '--radii-gravity-system-display-s-large',
        medium: '--radii-gravity-system-display-s-medium',
        small: '--radii-gravity-system-display-s-small',
        tiny: '--radii-gravity-system-display-s-tiny',
      },
      displayXL: {
        huge: '--radii-gravity-system-display-x-l-huge',
        large: '--radii-gravity-system-display-x-l-large',
        medium: '--radii-gravity-system-display-x-l-medium',
        small: '--radii-gravity-system-display-x-l-small',
        tiny: '--radii-gravity-system-display-x-l-tiny',
      },
      headlineL: {
        huge: '--radii-gravity-system-headline-l-huge',
        large: '--radii-gravity-system-headline-l-large',
        medium: '--radii-gravity-system-headline-l-medium',
        small: '--radii-gravity-system-headline-l-small',
        tiny: '--radii-gravity-system-headline-l-tiny',
      },
      headlineM: {
        huge: '--radii-gravity-system-headline-m-huge',
        large: '--radii-gravity-system-headline-m-large',
        medium: '--radii-gravity-system-headline-m-medium',
        small: '--radii-gravity-system-headline-m-small',
        tiny: '--radii-gravity-system-headline-m-tiny',
      },
      headlineS: {
        huge: '--radii-gravity-system-headline-s-huge',
        large: '--radii-gravity-system-headline-s-large',
        medium: '--radii-gravity-system-headline-s-medium',
        small: '--radii-gravity-system-headline-s-small',
        tiny: '--radii-gravity-system-headline-s-tiny',
      },
      headlineXL: {
        huge: '--radii-gravity-system-headline-x-l-huge',
        large: '--radii-gravity-system-headline-x-l-large',
        medium: '--radii-gravity-system-headline-x-l-medium',
        small: '--radii-gravity-system-headline-x-l-small',
        tiny: '--radii-gravity-system-headline-x-l-tiny',
      },
      headlineXS: {
        huge: '--radii-gravity-system-headline-x-s-huge',
        large: '--radii-gravity-system-headline-x-s-large',
        medium: '--radii-gravity-system-headline-x-s-medium',
        small: '--radii-gravity-system-headline-x-s-small',
        tiny: '--radii-gravity-system-headline-x-s-tiny',
      },
      headlineXXS: {
        huge: '--radii-gravity-system-headline-x-x-s-huge',
        large: '--radii-gravity-system-headline-x-x-s-large',
        medium: '--radii-gravity-system-headline-x-x-s-medium',
        small: '--radii-gravity-system-headline-x-x-s-small',
        tiny: '--radii-gravity-system-headline-x-x-s-tiny',
      },
    },
    semantic: {
      lg: '--radii-semantic-lg',
      md: '--radii-semantic-md',
      sm: '--radii-semantic-sm',
      xl: '--radii-semantic-xl',
      xs: '--radii-semantic-xs',
      xxl: '--radii-semantic-xxl',
      xxs: '--radii-semantic-xxs',
      xxxl: '--radii-semantic-xxxl',
      xxxs: '--radii-semantic-xxxs',
    },
    static: {
      x0: '--radii-static-x0',
      x05: '--radii-static-x05',
      x1: '--radii-static-x1',
      x10: '--radii-static-x10',
      x11: '--radii-static-x11',
      x12: '--radii-static-x12',
      x13: '--radii-static-x13',
      x14: '--radii-static-x14',
      x15: '--radii-static-x15',
      x16: '--radii-static-x16',
      x17: '--radii-static-x17',
      x18: '--radii-static-x18',
      x19: '--radii-static-x19',
      x2: '--radii-static-x2',
      x20: '--radii-static-x20',
      x3: '--radii-static-x3',
      x4: '--radii-static-x4',
      x5: '--radii-static-x5',
      x6: '--radii-static-x6',
      x7: '--radii-static-x7',
      x8: '--radii-static-x8',
      x9: '--radii-static-x9',
    },
  },
  rheaGray: {
    0: '--rhea-gray-0',
    50: '--rhea-gray-50',
    100: '--rhea-gray-100',
    200: '--rhea-gray-200',
    300: '--rhea-gray-300',
    400: '--rhea-gray-400',
    500: '--rhea-gray-500',
    600: '--rhea-gray-600',
    700: '--rhea-gray-700',
    800: '--rhea-gray-800',
    900: '--rhea-gray-900',
    950: '--rhea-gray-950',
    1000: '--rhea-gray-1000',
  },
  semantic: {
    background0: {
      brand: '--semantic-background0-brand',
      critical: '--semantic-background0-critical',
      info: '--semantic-background0-info',
      neutral: '--semantic-background0-neutral',
      primary: '--semantic-background0-primary',
      secondary: '--semantic-background0-secondary',
      success: '--semantic-background0-success',
      warning: '--semantic-background0-warning',
    },
    background1: {
      brand: '--semantic-background1-brand',
      critical: '--semantic-background1-critical',
      info: '--semantic-background1-info',
      neutral: '--semantic-background1-neutral',
      primary: '--semantic-background1-primary',
      secondary: '--semantic-background1-secondary',
      success: '--semantic-background1-success',
      warning: '--semantic-background1-warning',
    },
    background2: {
      brand: '--semantic-background2-brand',
      critical: '--semantic-background2-critical',
      info: '--semantic-background2-info',
      neutral: '--semantic-background2-neutral',
      primary: '--semantic-background2-primary',
      secondary: '--semantic-background2-secondary',
      success: '--semantic-background2-success',
      warning: '--semantic-background2-warning',
    },
    brand: {
      4: '--semantic-brand-4',
      8: '--semantic-brand-8',
      12: '--semantic-brand-12',
      16: '--semantic-brand-16',
      24: '--semantic-brand-24',
      32: '--semantic-brand-32',
      40: '--semantic-brand-40',
      primary: '--semantic-brand-primary',
      secondary: '--semantic-brand-secondary',
      tertiary: '--semantic-brand-tertiary',
    },
    brandConstant: {
      4: '--semantic-brand-constant-4',
      8: '--semantic-brand-constant-8',
      12: '--semantic-brand-constant-12',
      16: '--semantic-brand-constant-16',
      24: '--semantic-brand-constant-24',
      32: '--semantic-brand-constant-32',
      40: '--semantic-brand-constant-40',
      primary: '--semantic-brand-constant-primary',
      secondary: '--semantic-brand-constant-secondary',
      tertiary: '--semantic-brand-constant-tertiary',
    },
    constant: {
      4: '--semantic-constant-4',
      8: '--semantic-constant-8',
      12: '--semantic-constant-12',
      16: '--semantic-constant-16',
      24: '--semantic-constant-24',
      32: '--semantic-constant-32',
      40: '--semantic-constant-40',
      60: '--semantic-constant-60',
      70: '--semantic-constant-70',
      80: '--semantic-constant-80',
      90: '--semantic-constant-90',
      [dep]secondary: '--semantic-constant-[dep]secondary',
      primary: '--semantic-constant-primary',
      secondary: '--semantic-constant-secondary',
      tertiary: '--semantic-constant-tertiary',
    },
    constantInverted: {
      4: '--semantic-constant-inverted-4',
      8: '--semantic-constant-inverted-8',
      12: '--semantic-constant-inverted-12',
      16: '--semantic-constant-inverted-16',
      24: '--semantic-constant-inverted-24',
      32: '--semantic-constant-inverted-32',
      40: '--semantic-constant-inverted-40',
      60: '--semantic-constant-inverted-60',
      70: '--semantic-constant-inverted-70',
      primary: '--semantic-constant-inverted-primary',
      secondary: '--semantic-constant-inverted-secondary',
      tertiary: '--semantic-constant-inverted-tertiary',
    },
    critical: {
      4: '--semantic-critical-4',
      8: '--semantic-critical-8',
      12: '--semantic-critical-12',
      16: '--semantic-critical-16',
      24: '--semantic-critical-24',
      32: '--semantic-critical-32',
      40: '--semantic-critical-40',
      primary: '--semantic-critical-primary',
      secondary: '--semantic-critical-secondary',
      tertiary: '--semantic-critical-tertiary',
    },
    elevation0: {
      body: '--semantic-elevation0-body',
      borderClick: '--semantic-elevation0-border-click',
      borderHover: '--semantic-elevation0-border-hover',
      borderNormal: '--semantic-elevation0-border-normal',
    },
    elevation1: {
      bodyClick: '--semantic-elevation1-body-click',
      bodyHover: '--semantic-elevation1-body-hover',
      bodyNormal: '--semantic-elevation1-body-normal',
      borderClick: '--semantic-elevation1-border-click',
      borderHover: '--semantic-elevation1-border-hover',
      borderNormal: '--semantic-elevation1-border-normal',
    },
    gradient: {
      secondary: {
        end: '--semantic-gradient-secondary-end',
        start: '--semantic-gradient-secondary-start',
      },
    },
    icon: {
      brand: '--semantic-icon-brand',
      constantInvertedPrimary: '--semantic-icon-constant-inverted-primary',
      constantInvertedSecondary: '--semantic-icon-constant-inverted-secondary',
      constantPrimary: '--semantic-icon-constant-primary',
      constantSecondary: '--semantic-icon-constant-secondary',
      critical: '--semantic-icon-critical',
      info: '--semantic-icon-info',
      neutral: '--semantic-icon-neutral',
      placeholder: '--semantic-icon-placeholder',
      primary: '--semantic-icon-primary',
      primaryInverted: '--semantic-icon-primary-inverted',
      secondary: '--semantic-icon-secondary',
      secondaryInverted: '--semantic-icon-secondary-inverted',
      success: '--semantic-icon-success',
      warning: '--semantic-icon-warning',
    },
    info: {
      4: '--semantic-info-4',
      8: '--semantic-info-8',
      12: '--semantic-info-12',
      16: '--semantic-info-16',
      24: '--semantic-info-24',
      32: '--semantic-info-32',
      40: '--semantic-info-40',
      primary: '--semantic-info-primary',
      secondary: '--semantic-info-secondary',
      tertiary: '--semantic-info-tertiary',
    },
    neutral: {
      4: '--semantic-neutral-4',
      8: '--semantic-neutral-8',
      12: '--semantic-neutral-12',
      16: '--semantic-neutral-16',
      24: '--semantic-neutral-24',
      32: '--semantic-neutral-32',
      40: '--semantic-neutral-40',
      primary: '--semantic-neutral-primary',
      secondary: '--semantic-neutral-secondary',
      tertiary: '--semantic-neutral-tertiary',
    },
    overlay: {
      primary: '--semantic-overlay-primary',
    },
    primary: {
      4: '--semantic-primary-4',
      8: '--semantic-primary-8',
      12: '--semantic-primary-12',
      16: '--semantic-primary-16',
      24: '--semantic-primary-24',
      32: '--semantic-primary-32',
      40: '--semantic-primary-40',
      60: '--semantic-primary-60',
      70: '--semantic-primary-70',
      primary: '--semantic-primary-primary',
      secondary: '--semantic-primary-secondary',
      tertiary: '--semantic-primary-tertiary',
    },
    primaryInverted: {
      4: '--semantic-primary-inverted-4',
      8: '--semantic-primary-inverted-8',
      12: '--semantic-primary-inverted-12',
      16: '--semantic-primary-inverted-16',
      24: '--semantic-primary-inverted-24',
      32: '--semantic-primary-inverted-32',
      40: '--semantic-primary-inverted-40',
      60: '--semantic-primary-inverted-60',
      70: '--semantic-primary-inverted-70',
      primary: '--semantic-primary-inverted-primary',
      secondary: '--semantic-primary-inverted-secondary',
      tertiary: '--semantic-primary-inverted-tertiary',
    },
    success: {
      4: '--semantic-success-4',
      8: '--semantic-success-8',
      12: '--semantic-success-12',
      16: '--semantic-success-16',
      24: '--semantic-success-24',
      32: '--semantic-success-32',
      40: '--semantic-success-40',
      primary: '--semantic-success-primary',
      secondary: '--semantic-success-secondary',
      tertiary: '--semantic-success-tertiary',
    },
    text: {
      brand: '--semantic-text-brand',
      constantInvertedPrimary: '--semantic-text-constant-inverted-primary',
      constantInvertedSecondary: '--semantic-text-constant-inverted-secondary',
      constantPrimary: '--semantic-text-constant-primary',
      constantSecondary: '--semantic-text-constant-secondary',
      critical: '--semantic-text-critical',
      info: '--semantic-text-info',
      neutral: '--semantic-text-neutral',
      primary: '--semantic-text-primary',
      primaryInverted: '--semantic-text-primary-inverted',
      secondary: '--semantic-text-secondary',
      secondaryInverted: '--semantic-text-secondary-inverted',
      success: '--semantic-text-success',
      warning: '--semantic-text-warning',
    },
    transparent: {
      primary: '--semantic-transparent-primary',
    },
    warning: {
      4: '--semantic-warning-4',
      8: '--semantic-warning-8',
      12: '--semantic-warning-12',
      16: '--semantic-warning-16',
      24: '--semantic-warning-24',
      32: '--semantic-warning-32',
      40: '--semantic-warning-40',
      primary: '--semantic-warning-primary',
      secondary: '--semantic-warning-secondary',
      tertiary: '--semantic-warning-tertiary',
    },
  },
  shadows: {
    lg: {
      dropShadow1: {
        blur: '--shadows-lg-drop-shadow1-blur',
        drop: '--shadows-lg-drop-shadow1-drop',
        shiftX: '--shadows-lg-drop-shadow1-shift-x',
        shiftY: '--shadows-lg-drop-shadow1-shift-y',
      },
      dropShadow2: {
        blur: '--shadows-lg-drop-shadow2-blur',
        drop: '--shadows-lg-drop-shadow2-drop',
        shiftX: '--shadows-lg-drop-shadow2-shift-x',
        shiftY: '--shadows-lg-drop-shadow2-shift-y',
      },
      innerShadow: {
        blur: '--shadows-lg-inner-shadow-blur',
        inner: '--shadows-lg-inner-shadow-inner',
        shiftX: '--shadows-lg-inner-shadow-shift-x',
        shiftY: '--shadows-lg-inner-shadow-shift-y',
      },
    },
    md: {
      dropShadow1: {
        blur: '--shadows-md-drop-shadow1-blur',
        drop: '--shadows-md-drop-shadow1-drop',
        shiftX: '--shadows-md-drop-shadow1-shift-x',
        shiftY: '--shadows-md-drop-shadow1-shift-y',
      },
      dropShadow2: {
        blur: '--shadows-md-drop-shadow2-blur',
        drop: '--shadows-md-drop-shadow2-drop',
        shiftX: '--shadows-md-drop-shadow2-shift-x',
        shiftY: '--shadows-md-drop-shadow2-shift-y',
      },
      innerShadow: {
        blur: '--shadows-md-inner-shadow-blur',
        inner: '--shadows-md-inner-shadow-inner',
        shiftX: '--shadows-md-inner-shadow-shift-x',
        shiftY: '--shadows-md-inner-shadow-shift-y',
      },
    },
    sm: {
      dropShadow1: {
        blur: '--shadows-sm-drop-shadow1-blur',
        drop: '--shadows-sm-drop-shadow1-drop',
        shiftX: '--shadows-sm-drop-shadow1-shift-x',
        shiftY: '--shadows-sm-drop-shadow1-shift-y',
      },
      dropShadow2: {
        blur: '--shadows-sm-drop-shadow2-blur',
        drop: '--shadows-sm-drop-shadow2-drop',
        shiftX: '--shadows-sm-drop-shadow2-shift-x',
        shiftY: '--shadows-sm-drop-shadow2-shift-y',
      },
      innerShadow: {
        blur: '--shadows-sm-inner-shadow-blur',
        inner: '--shadows-sm-inner-shadow-inner',
        shiftX: '--shadows-sm-inner-shadow-shift-x',
        shiftY: '--shadows-sm-inner-shadow-shift-y',
      },
    },
    xxs: {
      dropShadow: {
        blur: '--shadows-xxs-drop-shadow-blur',
        drop1: '--shadows-xxs-drop-shadow-drop1',
        shiftX: '--shadows-xxs-drop-shadow-shift-x',
        shiftY: '--shadows-xxs-drop-shadow-shift-y',
      },
    },
  },
  sizes: {
    gravitySystem: {
      bodyL: '--sizes-gravity-system-body-l',
      bodyM: '--sizes-gravity-system-body-m',
      bodyS: '--sizes-gravity-system-body-s',
      bodyXL: '--sizes-gravity-system-body-x-l',
      displayL: '--sizes-gravity-system-display-l',
      displayM: '--sizes-gravity-system-display-m',
      displayS: '--sizes-gravity-system-display-s',
      displayXL: '--sizes-gravity-system-display-x-l',
      headlineL: '--sizes-gravity-system-headline-l',
      headlineM: '--sizes-gravity-system-headline-m',
      headlineS: '--sizes-gravity-system-headline-s',
      headlineXL: '--sizes-gravity-system-headline-x-l',
      headlineXS: '--sizes-gravity-system-headline-x-s',
      headlineXXS: '--sizes-gravity-system-headline-x-x-s',
    },
    semantic: {
      lg: '--sizes-semantic-lg',
      md: '--sizes-semantic-md',
      sm: '--sizes-semantic-sm',
      xl: '--sizes-semantic-xl',
      xs: '--sizes-semantic-xs',
      xxl: '--sizes-semantic-xxl',
      xxs: '--sizes-semantic-xxs',
      xxxl: '--sizes-semantic-xxxl',
      xxxs: '--sizes-semantic-xxxs',
    },
    static: {
      x0: '--sizes-static-x0',
      x05: '--sizes-static-x05',
      x1: '--sizes-static-x1',
      x10: '--sizes-static-x10',
      x11: '--sizes-static-x11',
      x12: '--sizes-static-x12',
      x13: '--sizes-static-x13',
      x14: '--sizes-static-x14',
      x15: '--sizes-static-x15',
      x16: '--sizes-static-x16',
      x17: '--sizes-static-x17',
      x18: '--sizes-static-x18',
      x19: '--sizes-static-x19',
      x2: '--sizes-static-x2',
      x20: '--sizes-static-x20',
      x3: '--sizes-static-x3',
      x4: '--sizes-static-x4',
      x5: '--sizes-static-x5',
      x6: '--sizes-static-x6',
      x7: '--sizes-static-x7',
      x8: '--sizes-static-x8',
      x9: '--sizes-static-x9',
    },
  },
  spaceGraphite: {
    0: '--space-graphite-0',
    100: '--space-graphite-100',
    200: '--space-graphite-200',
    300: '--space-graphite-300',
    400: '--space-graphite-400',
    500: '--space-graphite-500',
    600: '--space-graphite-600',
    700: '--space-graphite-700',
    800: '--space-graphite-800',
    900: '--space-graphite-900',
  },
  spaces: {
    gravitySystem: {
      bodyL: {
        huge: '--spaces-gravity-system-body-l-huge',
        large: '--spaces-gravity-system-body-l-large',
        medium: '--spaces-gravity-system-body-l-medium',
        paragraph: '--spaces-gravity-system-body-l-paragraph',
        small: '--spaces-gravity-system-body-l-small',
        tiny: '--spaces-gravity-system-body-l-tiny',
      },
      bodyM: {
        huge: '--spaces-gravity-system-body-m-huge',
        large: '--spaces-gravity-system-body-m-large',
        medium: '--spaces-gravity-system-body-m-medium',
        paragraph: '--spaces-gravity-system-body-m-paragraph',
        small: '--spaces-gravity-system-body-m-small',
        tiny: '--spaces-gravity-system-body-m-tiny',
      },
      bodyS: {
        huge: '--spaces-gravity-system-body-s-huge',
        large: '--spaces-gravity-system-body-s-large',
        medium: '--spaces-gravity-system-body-s-medium',
        paragraph: '--spaces-gravity-system-body-s-paragraph',
        small: '--spaces-gravity-system-body-s-small',
        tiny: '--spaces-gravity-system-body-s-tiny',
      },
      bodyXL: {
        huge: '--spaces-gravity-system-body-x-l-huge',
        large: '--spaces-gravity-system-body-x-l-large',
        medium: '--spaces-gravity-system-body-x-l-medium',
        paragraph: '--spaces-gravity-system-body-x-l-paragraph',
        small: '--spaces-gravity-system-body-x-l-small',
        tiny: '--spaces-gravity-system-body-x-l-tiny',
      },
      displayL: {
        huge: '--spaces-gravity-system-display-l-huge',
        large: '--spaces-gravity-system-display-l-large',
        medium: '--spaces-gravity-system-display-l-medium',
        paragraph: '--spaces-gravity-system-display-l-paragraph',
        small: '--spaces-gravity-system-display-l-small',
        tiny: '--spaces-gravity-system-display-l-tiny',
      },
      displayM: {
        huge: '--spaces-gravity-system-display-m-huge',
        large: '--spaces-gravity-system-display-m-large',
        medium: '--spaces-gravity-system-display-m-medium',
        paragraph: '--spaces-gravity-system-display-m-paragraph',
        small: '--spaces-gravity-system-display-m-small',
        tiny: '--spaces-gravity-system-display-m-tiny',
      },
      displayS: {
        huge: '--spaces-gravity-system-display-s-huge',
        large: '--spaces-gravity-system-display-s-large',
        medium: '--spaces-gravity-system-display-s-medium',
        paragraph: '--spaces-gravity-system-display-s-paragraph',
        small: '--spaces-gravity-system-display-s-small',
        tiny: '--spaces-gravity-system-display-s-tiny',
      },
      displayXL: {
        huge: '--spaces-gravity-system-display-x-l-huge',
        large: '--spaces-gravity-system-display-x-l-large',
        medium: '--spaces-gravity-system-display-x-l-medium',
        paragraph: '--spaces-gravity-system-display-x-l-paragraph',
        small: '--spaces-gravity-system-display-x-l-small',
        tiny: '--spaces-gravity-system-display-x-l-tiny',
      },
      headlineL: {
        huge: '--spaces-gravity-system-headline-l-huge',
        large: '--spaces-gravity-system-headline-l-large',
        medium: '--spaces-gravity-system-headline-l-medium',
        paragraph: '--spaces-gravity-system-headline-l-paragraph',
        small: '--spaces-gravity-system-headline-l-small',
        tiny: '--spaces-gravity-system-headline-l-tiny',
      },
      headlineM: {
        huge: '--spaces-gravity-system-headline-m-huge',
        large: '--spaces-gravity-system-headline-m-large',
        medium: '--spaces-gravity-system-headline-m-medium',
        paragraph: '--spaces-gravity-system-headline-m-paragraph',
        small: '--spaces-gravity-system-headline-m-small',
        tiny: '--spaces-gravity-system-headline-m-tiny',
      },
      headlineS: {
        huge: '--spaces-gravity-system-headline-s-huge',
        large: '--spaces-gravity-system-headline-s-large',
        medium: '--spaces-gravity-system-headline-s-medium',
        paragraph: '--spaces-gravity-system-headline-s-paragraph',
        small: '--spaces-gravity-system-headline-s-small',
        tiny: '--spaces-gravity-system-headline-s-tiny',
      },
      headlineXL: {
        huge: '--spaces-gravity-system-headline-x-l-huge',
        large: '--spaces-gravity-system-headline-x-l-large',
        medium: '--spaces-gravity-system-headline-x-l-medium',
        paragraph: '--spaces-gravity-system-headline-x-l-paragraph',
        small: '--spaces-gravity-system-headline-x-l-small',
        tiny: '--spaces-gravity-system-headline-x-l-tiny',
      },
      headlineXS: {
        huge: '--spaces-gravity-system-headline-x-s-huge',
        large: '--spaces-gravity-system-headline-x-s-large',
        medium: '--spaces-gravity-system-headline-x-s-medium',
        paragraph: '--spaces-gravity-system-headline-x-s-paragraph',
        small: '--spaces-gravity-system-headline-x-s-small',
        tiny: '--spaces-gravity-system-headline-x-s-tiny',
      },
      headlineXXS: {
        huge: '--spaces-gravity-system-headline-x-x-s-huge',
        large: '--spaces-gravity-system-headline-x-x-s-large',
        medium: '--spaces-gravity-system-headline-x-x-s-medium',
        paragraph: '--spaces-gravity-system-headline-x-x-s-paragraph',
        small: '--spaces-gravity-system-headline-x-x-s-small',
        tiny: '--spaces-gravity-system-headline-x-x-s-tiny',
      },
    },
    semantic: {
      lg: '--spaces-semantic-lg',
      md: '--spaces-semantic-md',
      sm: '--spaces-semantic-sm',
      xl: '--spaces-semantic-xl',
      xs: '--spaces-semantic-xs',
      xxl: '--spaces-semantic-xxl',
      xxs: '--spaces-semantic-xxs',
      xxxl: '--spaces-semantic-xxxl',
      xxxs: '--spaces-semantic-xxxs',
    },
    static: {
      x0: '--spaces-static-x0',
      x05: '--spaces-static-x05',
      x1: '--spaces-static-x1',
      x10: '--spaces-static-x10',
      x11: '--spaces-static-x11',
      x12: '--spaces-static-x12',
      x13: '--spaces-static-x13',
      x14: '--spaces-static-x14',
      x15: '--spaces-static-x15',
      x16: '--spaces-static-x16',
      x17: '--spaces-static-x17',
      x18: '--spaces-static-x18',
      x19: '--spaces-static-x19',
      x2: '--spaces-static-x2',
      x20: '--spaces-static-x20',
      x3: '--spaces-static-x3',
      x4: '--spaces-static-x4',
      x5: '--spaces-static-x5',
      x6: '--spaces-static-x6',
      x7: '--spaces-static-x7',
      x8: '--spaces-static-x8',
      x9: '--spaces-static-x9',
    },
  },
  titanGray: {
    0: '--titan-gray-0',
    50: '--titan-gray-50',
    100: '--titan-gray-100',
    200: '--titan-gray-200',
    300: '--titan-gray-300',
    400: '--titan-gray-400',
    500: '--titan-gray-500',
    600: '--titan-gray-600',
    700: '--titan-gray-700',
    800: '--titan-gray-800',
    900: '--titan-gray-900',
    950: '--titan-gray-950',
    1000: '--titan-gray-1000',
  },
  umberialSaphire: {
    0: '--umberial-saphire-0',
    50: '--umberial-saphire-50',
    100: '--umberial-saphire-100',
    200: '--umberial-saphire-200',
    300: '--umberial-saphire-300',
    400: '--umberial-saphire-400',
    500: '--umberial-saphire-500',
    600: '--umberial-saphire-600',
    700: '--umberial-saphire-700',
    800: '--umberial-saphire-800',
    900: '--umberial-saphire-900',
    950: '--umberial-saphire-950',
    1000: '--umberial-saphire-1000',
  },
  uranianAqua: {
    0: '--uranian-aqua-0',
    50: '--uranian-aqua-50',
    100: '--uranian-aqua-100',
    200: '--uranian-aqua-200',
    300: '--uranian-aqua-300',
    400: '--uranian-aqua-400',
    500: '--uranian-aqua-500',
    600: '--uranian-aqua-600',
    700: '--uranian-aqua-700',
    800: '--uranian-aqua-800',
    900: '--uranian-aqua-900',
    950: '--uranian-aqua-950',
    1000: '--uranian-aqua-1000',
  },
  venusOrange: {
    0: '--venus-orange-0',
    50: '--venus-orange-50',
    100: '--venus-orange-100',
    200: '--venus-orange-200',
    300: '--venus-orange-300',
    400: '--venus-orange-400',
    500: '--venus-orange-500',
    600: '--venus-orange-600',
    700: '--venus-orange-700',
    800: '--venus-orange-800',
    900: '--venus-orange-900',
    950: '--venus-orange-950',
    1000: '--venus-orange-1000',
  },
  white: '--white',
  xBase: {
    0: '--x-base-0',
    50: '--x-base-50',
    100: '--x-base-100',
    200: '--x-base-200',
    300: '--x-base-300',
    400: '--x-base-400',
    500: '--x-base-500',
    600: '--x-base-600',
    700: '--x-base-700',
    800: '--x-base-800',
    900: '--x-base-900',
    1000: '--x-base-1000',
    1100: '--x-base-1100',
    1200: '--x-base-1200',
    1300: '--x-base-1300',
    1400: '--x-base-1400',
    1500: '--x-base-1500',
    1600: '--x-base-1600',
    1700: '--x-base-1700',
    1800: '--x-base-1800',
    1900: '--x-base-1900',
    2000: '--x-base-2000',
  },
} as const

/**
 * Получить значение токена по пути
 */
export function getTokenValue(path: string): string {
  return getComputedStyle(document.documentElement).getPropertyValue(path)
}

/**
 * Установить режим xBase
 */
export function setXBaseMode(mode: XBaseMode): void {
  if (typeof document !== "undefined") {
    document.documentElement.setAttribute("data-xbase-mode", mode)
  }
}

/**
 * Установить режим semantic
 */
export function setSemanticMode(mode: SemanticMode): void {
  if (typeof document !== "undefined") {
    document.documentElement.setAttribute("data-semantic-mode", mode)
  }
}

/**
 * Получить текущий режим xBase
 */
export function getXBaseMode(): XBaseMode {
  if (typeof document === "undefined") return "4px"
  return (document.documentElement.getAttribute("data-xbase-mode") || "4px") as XBaseMode
}

/**
 * Получить текущий режим semantic
 */
export function getSemanticMode(): SemanticMode {
  if (typeof document === "undefined") return "classic"
  return (document.documentElement.getAttribute("data-semantic-mode") || "classic") as SemanticMode
}

/**
 * Инициализация дефолтных режимов
 */
export function initializeTokenModes(): void {
  if (typeof document === "undefined") return
  if (!document.documentElement.getAttribute("data-xbase-mode")) {
    setXBaseMode("4px")
  }
  if (!document.documentElement.getAttribute("data-semantic-mode")) {
    setSemanticMode("classic")
  }
}
