import type { Metadata } from "next";
import "./styles/globals.css";
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className="antialiased bg-neutral-950 text-neutral-50"
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
